#!/usr/bin/env python3
"""Populate papers.json from the surveyed methods (benchmark tables + prose)."""
import json, os
ROOT = "/home/claude/site"

US = "Unsupervised & Semi-Supervised"
WS = "Weakly Supervised"
TF = "Training-Free"
IT = "Instruction-Tuned"
OW = "Open-World / Open-Vocabulary"

# method, slug, paradigm, year, venue, modelTypes, training, tasks, datasets, taxonomy, badges, summary, is_lm, ref_url
M = [
# ---------------- Unsupervised & Semi-Supervised (Table 4 + Sec V.A) ----------------
("FutureFrame","futureframe",US,2018,"CVPR",["CNN"],"Semi-supervised (normal-only)",["Detection"],["UCSD Ped2","CUHK Avenue","ShanghaiTech"],
 US+" / Prediction-Based Normality","Non-LM baseline|Future-frame prediction",
 "Classical non-LM baseline. Detects anomalies via large future-frame prediction errors on events that cannot be forecast from normal training video.",False,"#ref-18"),
("MemAE","memae",US,2019,"ICCV",["Autoencoder"],"Semi-supervised (normal-only)",["Detection"],["UCSD Ped2","CUHK Avenue","ShanghaiTech"],
 US+" / Reconstruction-Based Normality","Non-LM baseline|Memory-augmented",
 "Classical non-LM baseline. Constrains reconstruction with a memory module of prototypical normal patterns to avoid reconstructing anomalies too well.",False,"#ref-73"),
("HyCoVAD","hycovad",US,2025,"arXiv",["SSL","LLM"],"Semi-supervised",["Detection","Explanation"],["ComplexVAD"],
 US+" / Detect-then-Validate","Hybrid SSL-LLM|Interaction anomalies|Rule validation",
 "Hybrid SSL-LLM model for complex interaction anomalies: a self-supervised detector selects suspicious frames, then a VLM/LLM validation stage uses refined captions and environment rules to decide whether the event is anomalous.",True,"#ref-74"),
("MLLM-EVAD","mllm-evad",US,2025,"arXiv",["MLLM"],"Semi-supervised (normal-only)",["Detection","Explanation"],["CUHK Avenue","ComplexVAD"],
 US+" / Semantic Normality Exemplars","Object-centric|MLLM descriptions|Exemplar matching",
 "Uses MLLM-generated descriptions of single-object activities and object-pair interactions as scene-specific normality exemplars; at inference, new descriptions are compared to compact nominal exemplar sets, yielding anomaly scores plus textual evidence.",True,"#ref-72"),
("SlowFastVAD","slowfastvad",US,2025,"arXiv",["VLM","LLM"],"Semi-supervised",["Detection","Explanation"],["UCSD Ped2","CUHK Avenue","ShanghaiTech","UBnormal"],
 US+" / RAG-Enhanced Reasoning","RAG|Fast-slow pipeline|Interpretable",
 "RAG-enhanced vision-language pipeline: a fast reconstruction detector flags ambiguous segments, which a slower VLM module resolves by retrieving normal and abnormal patterns from a scenario-specific knowledge base.",True,"#ref-75"),
("SFN-VAD","sfn-vad",US,2025,"arXiv",["VLM"],"Semi-supervised (normal-only)",["Detection"],["UCSD Ped2","CUHK Avenue","ShanghaiTech"],
 US+" / Prediction + Semantic Consistency","Tri-modal|Sparse filtering|Prediction error",
 "Fuses appearance, motion, and language-derived semantic cues in a tri-modal encoder; a multimodal decoder predicts next frame and semantic representation, and a Sparse Feature Filtering Module limits over-generalization to abnormal events.",True,"#ref-76"),
("VLAVAD","vlavad",US,2024,"BMVC",["VLM"],"Unsupervised",["Detection"],["CUHK Avenue"],
 US+" / Semantic Normality Modeling","VLM prompts|Selective Prompt Adapter|Sequence modeling",
 "Detects and tracks objects, queries a pretrained VLM with selected prompts per object crop, and detects anomalies via rare semantic responses and temporal inconsistency between predicted and observed semantic states.",True,"#ref-77"),
("Follow the Rules (AnomalyRuler)","follow-the-rules",US,2024,"ECCV",["VLM","LLM"],"Semi-supervised (few normal frames)",["Detection"],["UCSD Ped2","CUHK Avenue","ShanghaiTech","UBnormal"],
 US+" / Rule Induction","Induction-deduction|Scene rules|Robust reasoning",
 "From a few normal reference frames a VLM produces textual scene descriptions and an LLM derives scenario-specific normality rules; test-frame descriptions are matched against induced rules with perception smoothing and robust LLM reasoning.",True,"#ref-78"),
("Kim et al. (CLIP normality)","kim-clip-normality",US,2023,"Sensors",["CLIP"],"Unsupervised",["Detection"],["ShanghaiTech"],
 US+" / Text-Conditional Similarity","CLIP|ChatGPT descriptions|Text-conditional",
 "Compares frames or object crops against predefined natural-language descriptions of normal and abnormal situations generated with ChatGPT, learning a text-conditional similarity function without frame- or video-level labels.",True,"#ref-80"),

# ---------------- Weakly Supervised (Table 5 + Sec V.B) ----------------
("DeepMIL","deepmil",WS,2018,"CVPR",["CNN"],"Weakly supervised (MIL)",["Detection"],["UCF-Crime"],
 WS+" / Multiple Instance Learning","Non-LM baseline|Seminal MIL",
 "Seminal non-LM baseline formulating weakly supervised VAD as multiple instance learning over bags of temporal instances.",False,"#ref-19"),
("MSL","msl",WS,2022,"AAAI",["Transformer"],"Weakly supervised (MIL)",["Detection"],["UCF-Crime","XD-Violence","ShanghaiTech"],
 WS+" / Self-Training","Non-LM baseline|Multi-sequence learning",
 "Non-LM baseline: self-training multi-sequence learning with a transformer for weakly supervised VAD.",False,"#ref-82"),
("MIST","mist",WS,2021,"arXiv",["CNN"],"Weakly supervised (MIL)",["Detection"],["UCF-Crime","ShanghaiTech"],
 WS+" / Self-Training","Non-LM baseline|Multiple-instance self-training",
 "Non-LM baseline: multiple instance self-training framework for video anomaly detection.",False,"#ref-83"),
("GCN","gcn",WS,2019,"CVPR",["GCN"],"Weakly supervised",["Detection"],["UCF-Crime","ShanghaiTech"],
 WS+" / Graph Reasoning","Non-LM baseline|Label-noise cleaning",
 "Non-LM baseline: graph convolutional label-noise cleaner training a plug-and-play action classifier for anomaly detection.",False,"#ref-84"),
("VadCLIP","vadclip",WS,2024,"AAAI",["CLIP"],"Weakly supervised (MIL)",["Detection","Classification"],["UCF-Crime","XD-Violence"],
 WS+" / Vision-Language Adaptation","CLIP|Dual-branch|MIL-Align|Learnable prompts",
 "Dual-branch framework combining a visual classification branch with a vision-language alignment branch; adds a local-global temporal adapter, learnable prompts, anomaly-focused visual prompts, and a MIL-Align objective for video-text alignment.",True,"#ref-81"),
("VadCLIP++","vadclip-plus",WS,2025,"Digital Signal Processing",["CLIP"],"Weakly supervised",["Detection","Classification"],["UCF-Crime","XD-Violence"],
 WS+" / Vision-Language Adaptation","CLIP|Dynamic VLM|Temporal modeling",
 "Extends VadCLIP with a dynamic vision-language model for weakly supervised temporal anomaly localization.",True,"#ref-92"),
("CLIP-TSA","clip-tsa",WS,2024,"ICIP",["CLIP"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence","ShanghaiTech"],
 WS+" / Vision-Language Adaptation","CLIP|Temporal self-attention",
 "CLIP-assisted temporal self-attention for weakly-supervised VAD.",True,"#ref-97"),
("ReFLIP-VAD","reflip-vad",WS,2024,"IEEE TCSVT",["VLM"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Vision-Language Adaptation","VLM|Frame-label alignment",
 "Weakly supervised VAD via a vision-language model with refined frame-label alignment.",True,"#ref-98"),
("PEMIL","pemil",WS,2024,"IEEE TIP",["VLM"],"Weakly supervised (MIL)",["Detection","Classification"],["UCF-Crime","XD-Violence","ShanghaiTech"],
 WS+" / Prompt-Enhanced MIL","Prompt-enhanced|Temporal context|Commonsense prompts",
 "Combines a Temporal Context Aggregation module with a Prompt-Enhanced Learning module that builds knowledge-based prompts from external commonsense concepts to improve fine-grained discriminability among anomaly categories.",True,"#ref-96"),
("TEVAD","tevad",WS,2023,"CVPR",["Captioning"],"Weakly supervised (MIL)",["Detection","Explanation"],["UCF-Crime"],
 WS+" / Caption-Guided Semantics","Dense captions|Sentence embeddings|Interpretability",
 "Generates dense captions for snippets, encodes them as sentence embeddings, and fuses textual and visual features before MIL scoring, improving detection and offering caption-level interpretability.",True,"#ref-103"),
("Ex-VAD","ex-vad",WS,2025,"ICML",["VLM","LLM"],"Weakly supervised",["Detection","Explanation","Classification"],["UCF-Crime","XD-Violence"],
 WS+" / LLM Knowledge Enhancement","Frame captions|LLM explanations|Label augmentation",
 "Uses a VLM for frame-level captions and an LLM to convert them into video-level anomaly explanations, and augments category labels with LLM-generated descriptive phrases for fine-grained classification.",True,"#ref-87"),
("DAKD","dakd",WS,2025,"WACV",["VLM"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence","ShanghaiTech"],
 WS+" / Knowledge Distillation","Aggregated knowledge|Distillation",
 "Distilling aggregated knowledge for weakly-supervised VAD.",True,"#ref-85"),
("LEC-VAD","lec-vad",WS,2025,"arXiv",["VLM"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Caption-Guided Semantics","Event completeness|Semantic guidance",
 "Learns event completeness for weakly supervised VAD.",True,"#ref-86"),
("LOP-VAD","lop-vad",WS,2025,"Knowledge-Based Systems",["VLM"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Prompt-Enhanced MIL","Opposite prompts|Prompt learning",
 "Learns opposite prompts for weakly supervised VAD.",True,"#ref-89"),
("TCRFL","tcrfl",WS,2025,"J. Information and Intelligence",["VLM"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence","ShanghaiTech"],
 WS+" / Caption-Guided Semantics","Temporal context|Representative features",
 "Temporal context and representative feature learning for weakly supervised VAD.",True,"#ref-90"),
("FSA-VAD","fsa-vad",WS,2025,"ICIC",["VLM"],"Weakly supervised",["Detection"],["ShanghaiTech"],
 WS+" / Caption-Guided Semantics","Filter-summarize-align|Semantic guidance",
 "Filter, summarize, align: semantic-guided weakly supervised VAD.",True,"#ref-91"),
("RelVid","relvid",WS,2025,"Sensors",["CLIP"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Relation-Aware","Relational learning|Auxiliary objectives",
 "Relational learning with vision-language models plus auxiliary anomaly-recognition and reconstruction objectives to improve class separation and temporal feature learning.",True,"#ref-93"),
("AVadCLIP","avadclip",WS,2025,"arXiv",["CLIP","Audio"],"Weakly supervised",["Detection"],["XD-Violence"],
 WS+" / Multimodal Fusion","Audio-visual fusion|Uncertainty distillation",
 "Audio-visual collaboration on a CLIP backbone: adaptive audio-visual fusion and an audio-visual prompt, with uncertainty-driven feature distillation to a visual-only student when audio is unavailable.",True,"#ref-94"),
("Multimodal-VAD","multimodal-vad",WS,2025,"IEEE TIM",["VLM","Audio"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Multimodal Fusion","Audio-vision-language|Intelligent monitoring",
 "Visual anomaly detection in an intelligent monitoring system via audio-vision-language fusion.",True,"#ref-95"),
("Federated-WVAD","federated-wvad",WS,2025,"AAAI",["VLM"],"Weakly supervised (federated)",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Prompt-Enhanced MIL","Federated learning|Multimodal prompt",
 "Federated weakly supervised VAD with a multimodal prompt.",True,"#ref-88"),
("IELD-WVAD","ield-wvad",WS,2024,"arXiv",["VLM"],"Weakly supervised",["Detection","Explanation"],["UCF-Crime","XD-Violence"],
 WS+" / LLM Knowledge Enhancement","Explainability|Lightweight design",
 "Injects explainability and lightweight design into weakly supervised VAD systems.",True,"#ref-99"),
("DWFF-VAD","dwff-vad",WS,2024,"ICCE-Asia",["VLM"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Multimodal Fusion","Dynamic-weighted fusion",
 "Weakly supervised VAD using dynamic-weighted feature fusion.",True,"#ref-100"),
("CMSIL","cmsil",WS,2024,"ICME",["CLIP"],"Weakly supervised (MIL)",["Detection"],["UCF-Crime","XD-Violence"],
 WS+" / Vision-Language Adaptation","CLIP-driven|Multi-scale instance learning",
 "CLIP-driven multi-scale instance learning for weakly supervised VAD.",True,"#ref-101"),
("WSVAD-LLMKE","wsvad-llmke",WS,2024,"ICTAI",["LLM"],"Weakly supervised",["Detection"],["UCF-Crime","XD-Violence","ShanghaiTech"],
 WS+" / LLM Knowledge Enhancement","LLM knowledge|Enhancement framework",
 "Weakly supervised VAD with a large language model knowledge enhancement framework.",True,"#ref-102"),
("CALLM","callm",WS,2024,"IPTA",["LLM"],"Weakly supervised",["Detection","Explanation"],["UCF-Crime"],
 WS+" / LLM Knowledge Enhancement","3D autoencoder|Video-LLaMA|Pseudo-instruction",
 "Cascaded design where a 3D autoencoder flags suspicious frames and a Video-LLaMA branch provides abnormality decisions and explanations via weakly supervised pseudo-instruction tuning.",True,"#ref-113"),
("MissionGNN","missiongnn",WS,2025,"WACV",["LLM","GNN"],"Weakly supervised",["Detection","Classification"],["UCF-Crime"],
 WS+" / Relation-Aware","Knowledge graphs|Hierarchical GNN|ConceptNet",
 "Generates mission-specific knowledge graphs with an LLM and ConceptNet, then applies hierarchical GNNs for weakly supervised anomaly recognition.",True,"#ref-116"),
("ALAN","alan",WS,2024,"IEEE TIP",["VLM"],"Weakly supervised",["Retrieval","Grounding"],["UCF-Crime"],
 WS+" / Anomaly Retrieval","Video anomaly retrieval|Cross-modal alignment",
 "Shifts from detection to video anomaly retrieval: long untrimmed videos are retrieved by textual or audio queries with anomaly-led sampling and cross-modal alignment.",True,"#ref-117"),

# ---------------- Training-Free (Table 6 full training-free + Sec V.C) ----------------
("LAVAD","lavad",TF,2024,"CVPR",["VLM","LLM"],"Training-free",["Detection","Temporal localization","Explanation"],["UCF-Crime","XD-Violence","UBnormal"],
 TF+" / Caption-Based Temporal Reasoning","Caption-based|LLM reasoning|Cross-modal refinement",
 "Converts VAD into a language-based reasoning problem: frame captions from an off-the-shelf VLM are cleaned by image-text similarity, an LLM summarizes them over temporal windows to score anomalies, and scores are refined via cross-modal similarity.",True,"#ref-118"),
("VERA","vera",TF,2025,"CVPR",["VLM"],"Training-free",["Detection","Explanation"],["UCF-Crime","XD-Violence"],
 TF+" / Verbalized Reasoning","Guiding questions|Prompt adaptation|Explainable",
 "Explainable training-free VAD that learns natural-language guiding questions to elicit anomaly-relevant reasoning from frozen VLMs, adapting the prompt space with coarsely labeled data.",True,"#ref-130"),
("SUVAD","suvad",TF,2025,"ICASSP",["MLLM"],"Training-free",["Detection","Explanation"],["UCF-Crime","XD-Violence"],
 TF+" / Semantic Understanding","MLLM|Event lists|Flexible definitions",
 "Semantic-understanding VAD with MLLMs: generates textual descriptions of normal and abnormal events, compares test-video descriptions against event lists, and supports flexible anomaly definitions.",True,"#ref-131"),
("EventVAD","eventvad",TF,2025,"ACM MM",["MLLM"],"Training-free",["Detection","Temporal localization"],["UCF-Crime","XD-Violence"],
 TF+" / Event-Aware Reasoning","Event segmentation|Spatiotemporal graph|Hierarchical prompting",
 "Segments long videos into event-consistent units via dynamic spatiotemporal graph modeling, statistical boundary detection, and hierarchical prompting before anomaly scoring.",True,"#ref-127"),
("MCANet","mcanet",TF,2024,"ICPR",["LLM","Audio"],"Training-free",["Detection"],["UCF-Crime","XD-Violence","UBnormal"],
 TF+" / Multimodal Caption-Aware","Multimodal|Caption-aware|Audio",
 "Multimodal caption-aware training-free VAD combining visual, audio, and language cues via a large language model.",True,"#ref-132"),
("Flashback","flashback",TF,2025,"arXiv",["LLM","Cross-modal"],"Training-free",["Detection","Explanation"],["UCF-Crime","XD-Violence"],
 TF+" / Memory-Driven","Offline pseudo-scene memory|Real-time|Similarity search",
 "Builds an offline pseudo-scene memory of LLM-generated normal and anomalous captions embedded with a frozen encoder; online segments are matched by similarity search, removing expensive online LLM calls for real-time zero-shot VAD.",True,"#ref-124"),
("PANDA","panda",TF,2025,"NeurIPS",["MLLM","Agent"],"Training-free (agentic)",["Detection","Explanation"],["UCF-Crime","XD-Violence","UBnormal"],
 TF+" / Agentic Pipelines","Agentic AI|Generalist VAD",
 "Agentic AI engineer for generalist training-free video anomaly detection.",True,"#ref-128"),
("QVAD","qvad",TF,2026,"arXiv",["VLM","Agent"],"Training-free (agentic)",["Detection","Retrieval","Grounding"],["UCF-Crime","XD-Violence","UBnormal"],
 TF+" / Agentic Pipelines","Question-centric|Agentic|Efficient",
 "Question-centric agentic framework for efficient and training-free video anomaly detection.",True,"#ref-123"),
("VADTree","vadtree",TF,2025,"NeurIPS",["MLLM"],"Training-free",["Detection","Explanation"],["UCF-Crime","XD-Violence"],
 TF+" / Hierarchical Reasoning","Granularity-aware tree|Explainable",
 "Explainable training-free VAD via a hierarchical granularity-aware tree.",True,"#ref-129"),
("MoniTor","monitor",TF,2025,"NeurIPS",["LLM"],"Training-free (online)",["Detection"],["UCF-Crime","XD-Violence"],
 TF+" / Online Reasoning","Instruction|Online VAD",
 "Exploits large language models with instruction for online video anomaly detection.",True,"#ref-126"),
("TFPLG","tfplg",TF,2025,"IEEE Access",["VLM"],"Training-free (pseudo-label)",["Detection"],["UCF-Crime","XD-Violence"],
 TF+" / Pseudo-Label Generation","VLM|Pseudo labels|Auxiliary supervision",
 "Training-free VLM-based pseudo-label generation producing auxiliary supervision for downstream VAD.",True,"#ref-125"),
("AnyAnomaly","anyanomaly",TF,2026,"WACV",["LVLM"],"Training-free (customizable)",["Detection","Question answering"],["UCF-Crime"],
 TF+" / Customizable Reasoning","Customizable VAD|Context-aware VQA|Key frames",
 "Customizable VAD where user text defines the abnormal event; performs segment-level context-aware VQA with an LVLM without fine-tuning, using key-frame selection and grid-format temporal context.",True,"#ref-133"),
("Anomaly-OV","anomaly-ov",TF,2025,"CVPR",["MLLM"],"Training-free (zero-shot)",["Detection","Explanation"],["UCF-Crime"],
 TF+" / Open-Ended Reasoning","Zero-shot|Visual token selection|Reasoning",
 "Studies zero-shot anomaly detection and reasoning with MLLMs, introducing anomaly-specific instruction data and a specialist visual assistant that selects suspicious visual tokens for detection and explanation.",True,"#ref-134"),
("VisionGPT","visiongpt",TF,2024,"arXiv",["LLM"],"Training-free",["Detection"],["UCF-Crime"],
 TF+" / Application-Specific","LLM-assisted|Safe navigation",
 "Applies LLM-assisted anomaly detection to safe visual navigation.",True,"#ref-138"),

# ---------------- Instruction-Tuned (Sec V.D) ----------------
("Holmes-VAD","holmes-vad",IT,2024,"arXiv",["MLLM"],"Instruction tuning",["Detection","Explanation","Question answering"],["UCF-Crime","XD-Violence"],
 IT+" / Anomaly Understanding","VADInstruct50K|Temporal sampler|LoRA",
 "Constructs the VADInstruct50K instruction-tuning benchmark and trains a temporal sampler plus a LoRA-tuned multimodal LLM to produce anomaly judgments and explanations, addressing both when and why an event is abnormal.",True,"#ref-122"),
("Holmes-VAU","holmes-vau",IT,2025,"CVPR",["MLLM"],"Instruction tuning",["Detection","Explanation"],["UCF-Crime","XD-Violence"],
 IT+" / Any-Granularity Understanding","HIVAU-70K|Anomaly-focused sampler|Hierarchical",
 "Introduces the HIVAU-70K hierarchical instruction benchmark (clip/event/video-level) and an Anomaly-focused Temporal Sampler that adaptively selects informative frames for long-video, multi-granularity anomaly understanding.",True,"#ref-61"),
("HAWK","hawk",IT,2024,"NeurIPS",["VLM"],"Instruction tuning",["Explanation","Question answering"],["UCF-Crime"],
 IT+" / Open-World Understanding","Motion-language|Multi-dataset QA",
 "Fine-tunes a VLM on anomaly descriptions and QA pairs from multiple VAD datasets, incorporating motion information and motion-language supervision to better describe abnormal events.",True,"#ref-140"),
("AssistPDA","assistpda",IT,2025,"arXiv",["MLLM"],"Instruction tuning (online)",["Detection","Explanation","Question answering"],["UCF-Crime"],
 IT+" / Online Assistance","VAPDA-127K|Streaming|Spatiotemporal relation distillation",
 "Shifts from offline analysis to online surveillance assistance, unifying anomaly prediction, detection, and analysis in streaming video via VAPDA-127K and a spatiotemporal relation distillation module.",True,"#ref-141"),
("Vad-R1","vad-r1",IT,2026,"NeurIPS",["MLLM"],"Instruction tuning + RL",["Detection","Reasoning","Explanation"],["UCF-Crime"],
 IT+" / Anomaly Reasoning","Perception-to-Cognition CoT|AVA-GRPO|Reasoning",
 "Introduces Video Anomaly Reasoning with a Perception-to-Cognition Chain-of-Thought; trained with supervised fine-tuning then reinforcement learning (AVA-GRPO) using an anomaly-verification reward.",True,"#ref-142"),
("VAU-R1","vau-r1",IT,2025,"arXiv",["MLLM"],"Instruction tuning + RL",["Question answering","Grounding","Reasoning","Classification"],["UCF-Crime"],
 IT+" / Anomaly Reasoning","Reinforcement fine-tuning|GRPO|Multi-task",
 "Reinforcement fine-tuning that decomposes anomaly understanding into multiple-choice QA, temporal grounding, reasoning, and classification, applying GRPO with task-specific rewards.",True,"#ref-143"),
("Sherlock","sherlock",IT,2025,"ACM Web Conf",["LLM"],"Instruction tuning",["Detection","Grounding","Classification"],["UCF-Crime"],
 IT+" / Structured Extraction","Multi-scene|Quadruple extraction|Spatial experts",
 "Multi-scene abnormal event extraction and localization: a global-local spatial-sensitive LLM with spatial experts extracts a subject/event-type/object/scene quadruple, balanced by a spatial imbalance regulator.",True,"#ref-144"),

# ---------------- Open-World / Open-Vocabulary (Table 6 open-world + Sec V.E) ----------------
("OVVAD","ovvad",OW,2024,"CVPR",["CLIP","LLM"],"Open-vocabulary",["Detection","Classification"],["UCF-Crime","XD-Violence","UBnormal"],
 OW+" / Detect + Categorize","Class-agnostic detection|Novel-anomaly synthesis|Semantic injection",
 "Formulates open-vocabulary VAD as joint detection and categorization: class-agnostic detection using CLIP features plus a semantic knowledge injection module, and class-specific categorization with an LLM/generative novel-anomaly synthesis module.",True,"#ref-119"),
("Anomize","anomize",OW,2025,"CVPR",["VLM"],"Open-vocabulary",["Detection","Classification"],["UCF-Crime","XD-Violence"],
 OW+" / Novel-Category Alignment","Dual-stream|Group-guided text encoding",
 "Targets detection ambiguity and categorization confusion in OV-VAD via a text-augmented dual-stream design and a group-guided text encoding mechanism that uses label relations to align novel videos and labels.",True,"#ref-120"),
("PLOVAD","plovad",OW,2025,"IEEE TCSVT",["VLM"],"Open-vocabulary (prompt tuning)",["Detection","Classification"],["UCF-Crime"],
 OW+" / Prompt Adaptation","Domain prompt|LLM anomaly prompt|GAT temporal",
 "Adapts image-based VLMs to OV-VAD via prompt tuning: a learnable domain-specific prompt and an LLM-generated anomaly-specific prompt, with a GAT-based temporal module for video-level localization.",True,"#ref-121"),
("MEL-VLP","mel-vlp",OW,2025,"IEEE TMM",["CLIP"],"Open-world weakly supervised",["Detection"],["UCF-Crime","XD-Violence"],
 OW+" / Uncertainty Calibration","Evidential learning|Multi-scale|Boundary calibration",
 "Open-world weakly supervised setting using multi-scale temporal modeling and multimodal evidential collaborative learning to estimate uncertainty and dynamically calibrate anomaly boundaries.",True,"#ref-145"),
("LaGoVAD","lagovad",OW,2025,"arXiv",["VLM"],"Open-world (language-guided)",["Detection","Classification","Grounding"],["UCF-Crime"],
 OW+" / Language-Guided Definitions","Variable anomaly definitions|Video-text fusion|PreVAD",
 "Language-guided open-world VAD with variable anomaly definitions: conditions detection on user-provided natural-language definitions at inference, supported by the large-scale PreVAD dataset.",True,"#ref-146"),
]

papers = []
for (method,slug,paradigm,year,venue,models,training,tasks,datasets,taxonomy,badges,summary,is_lm,ref) in M:
    refid = ref.replace("#ref-","")
    url = f"/survey/full/{ref}"
    papers.append({
        "slug": slug,
        "method": method,
        "title": summary.split(".")[0] if False else method,  # title set below
        "authors": ["See reference ["+refid+"]"],
        "venue": venue,
        "year": year,
        "paradigm": paradigm,
        "modelTypes": models,
        "training": training,
        "tasks": tasks,
        "datasets": datasets,
        "summary": summary,
        "taxonomy": taxonomy,
        "badges": badges.split("|"),
        "code": False,
        "paperUrl": url,
        "added": "v1.0",
        "updated": "v1.0",
        "verified": "Sourced from survey PDF",
        "status": "From survey PDF — verify links",
        "isLM": is_lm,
    })

# Give each a descriptive title (method + short descriptor from taxonomy leaf)
for p in papers:
    leaf = p["taxonomy"].split(" / ")[-1]
    p["title"] = f"{p['method']} — {leaf}"

# Validate unique slugs
slugs = [p["slug"] for p in papers]
assert len(slugs) == len(set(slugs)), "duplicate slugs!"

with open(os.path.join(ROOT,"data/papers.json"),"w") as f:
    json.dump(papers, f, indent=1, ensure_ascii=False)

from collections import Counter
byp = Counter(p["paradigm"] for p in papers)
lm = sum(1 for p in papers if p["isLM"])
print(f"papers.json: {len(papers)} methods ({lm} LM-based, {len(papers)-lm} non-LM baselines)")
for k,v in byp.items(): print(f"  {k}: {v}")
