#!/usr/bin/env python3
"""Populate references.json with all 167 references from the survey PDF bibliography.
Author strings use the initials-based form from the paper; long lists use 'et al.'
Titles and venues are transcribed as printed. Verify against originals before release."""
import json, os
ROOT = "/home/claude/site"

# (id, authors, title, venue, url)
R = [
(1,"V. Chandola, A. Banerjee, V. Kumar","Anomaly detection: A survey","ACM Computing Surveys, 41(3):1-58, 2009",""),
(2,"L. Ruff, J. R. Kauffmann, R. A. Vandermeulen, et al.","A unifying review of deep and shallow anomaly detection","Proceedings of the IEEE, 109(5):756-795, 2021",""),
(3,"C. Stauffer, W. E. L. Grimson","Adaptive background mixture models for real-time tracking","CVPR, 1999, pp. 246-252",""),
(4,"W. Hu, T. Tan, L. Wang, S. Maybank","A survey on visual surveillance of object motion and behaviors","IEEE Trans. Systems, Man, and Cybernetics, Part C, 34(3):334-352, 2004",""),
(5,"B. T. Morris, M. M. Trivedi","A survey of vision-based trajectory learning and analysis for surveillance","IEEE Trans. Circuits and Systems for Video Technology, 18(8):1114-1127, 2008",""),
(6,"O. Boiman, M. Irani","Detecting irregularities in images and in video","IJCV, 74(1):17-31, 2007",""),
(7,"A. Adam, E. Rivlin, I. Shimshoni, D. Reinitz","Robust real-time unusual event detection using multiple fixed-location monitors","IEEE TPAMI, 30(3):555-560, 2008",""),
(8,"L. Kratz, K. Nishino","Anomaly detection in extremely crowded scenes using spatio-temporal motion pattern models","CVPR, 2009, pp. 1446-1453",""),
(9,"R. Mehran, A. Oyama, M. Shah","Abnormal crowd behavior detection using social force model","CVPR, 2009, pp. 935-942",""),
(10,"J. Kim, K. Grauman","Observe locally, infer globally: A space-time MRF for detecting abnormal activities with incremental updates","CVPR, 2009, pp. 2921-2928",""),
(11,"V. Mahadevan, W. Li, V. Bhalodia, N. Vasconcelos","Anomaly detection in crowded scenes","CVPR, 2010, pp. 1975-1981",""),
(12,"S. Wu, B. E. Moore, M. Shah","Chaotic invariants of Lagrangian particle trajectories for anomaly detection in crowded scenes","CVPR, 2010, pp. 2054-2060",""),
(13,"Y. Cong, J. Yuan, J. Liu","Sparse reconstruction cost for abnormal event detection","CVPR, 2011, pp. 3449-3456",""),
(14,"V. Saligrama, Z. Chen","Video anomaly detection based on local statistical aggregates","CVPR, 2012, pp. 2112-2119",""),
(15,"M. J. Roshtkhari, M. D. Levine","An on-line, real-time learning method for detecting anomalies in videos using spatio-temporal compositions","CVIU, 117(10):1436-1452, 2013",""),
(16,"W. Luo, W. Liu, S. Gao","Remembering history with convolutional LSTM for anomaly detection","ICME, 2017, pp. 439-444",""),
(17,"M. Hasan, J. Choi, J. Neumann, A. K. Roy-Chowdhury, L. S. Davis","Learning temporal regularity in video sequences","CVPR, 2016, pp. 733-742",""),
(18,"W. Liu, W. Luo, D. Lian, S. Gao","Future frame prediction for anomaly detection - a new baseline","CVPR, 2018, pp. 6536-6545",""),
(19,"W. Sultani, C. Chen, M. Shah","Real-world anomaly detection in surveillance videos","CVPR, 2018, pp. 6479-6488",""),
(20,"C. Lu, J. Shi, J. Jia","Abnormal event detection at 150 fps in MATLAB","ICCV, 2013, pp. 2720-2727",""),
(21,"A. Radford, J. W. Kim, C. Hallacy, et al.","Learning transferable visual models from natural language supervision","ICML, 2021, pp. 8748-8763",""),
(22,"J. Li, D. Li, S. Savarese, S. Hoi","BLIP-2: Bootstrapping language-image pre-training with frozen image encoders and large language models","ICML, 2023, pp. 19730-19742",""),
(23,"J.-B. Alayrac, J. Donahue, P. Luc, et al.","Flamingo: a visual language model for few-shot learning","NeurIPS, 35:23716-23736, 2022",""),
(24,"H. Liu, C. Li, Q. Wu, Y. J. Lee","Visual instruction tuning","NeurIPS, 36:34892-34916, 2023",""),
(25,"B. Lin, Y. Ye, B. Zhu, et al.","Video-LLaVA: Learning united visual representation by alignment before projection","EMNLP, 2024, pp. 5971-5984",""),
(26,"M. Maaz, H. Rasheed, S. Khan, F. Khan","Video-ChatGPT: Towards detailed video understanding via large vision and language models","ACL, 2024, pp. 12585-12602",""),
(27,"B. Ramachandra, M. J. Jones, R. R. Vatsavai","A survey of single-scene video anomaly detection","IEEE TPAMI, 44(5):2293-2312, 2020",""),
(28,"R. Nayak, U. C. Pati, S. K. Das","A comprehensive review on deep learning-based methods for video anomaly detection","Image and Vision Computing, 106:104078, 2021",""),
(29,"T. M. Tran, T. N. Vu, N. D. Vo, T. V. Nguyen, K. Nguyen","Anomaly analysis in images and videos: A comprehensive review","ACM Computing Surveys, 55(7):1-37, 2022",""),
(30,"Y. Liu, D. Yang, Y. Wang, et al.","Generalized video anomaly event detection: Systematic taxonomy and comparison of deep models","ACM Computing Surveys, 56(7):1-38, 2024",""),
(31,"P. Wu, C. Pan, Y. Yan, G. Pang, Q. Yan, P. Wang, Y. Zhang","Deep learning for video anomaly detection: A review","IEEE Trans. Neural Networks and Learning Systems, 2026",""),
(32,"M. Abdalla, S. Javed, M. Al Radi, A. Ulhaq, N. Werghi","Video anomaly detection in 10 years: A survey and outlook","Neural Computing and Applications, 37(32):26321-26364, 2025",""),
(33,"X. Ding, L. Wang","Quo vadis, anomaly detection? LLMs and VLMs in the spotlight","arXiv:2412.18298, 2024","https://arxiv.org/abs/2412.18298"),
(34,"J. Liu, Y. Liu, J. Lin, et al.","Networking systems for video anomaly detection: A tutorial and survey","ACM Computing Surveys, 57(10):1-37, 2025",""),
(35,"S. Gao, P. Yang, H. Guo, et al.","The evolution of video anomaly detection: A unified framework from DNN to MLLM","arXiv:2507.21649, 2025","https://arxiv.org/abs/2507.21649"),
(36,"F. Mumcu, L. Bekit, M. J. Jones, A. Cherian, Y. Yilmaz","Agentic AI-empowered dynamic survey framework","arXiv:2602.04071, 2026","https://arxiv.org/abs/2602.04071"),
(37,"B. Scholkopf, J. C. Platt, J. Shawe-Taylor, A. J. Smola, R. C. Williamson","Estimating the support of a high-dimensional distribution","Neural Computation, 13(7):1443-1471, 2001",""),
(38,"D. M. J. Tax, R. P. W. Duin","Support vector data description","Machine Learning, 54(1):45-66, 2004",""),
(39,"L. Ruff, R. Vandermeulen, N. Goernitz, et al.","Deep one-class classification","ICML, 2018, pp. 4393-4402",""),
(40,"T. G. Dietterich, R. H. Lathrop, T. Lozano-Perez","Solving the multiple instance problem with axis-parallel rectangles","Artificial Intelligence, 89(1-2):31-71, 1997",""),
(41,"S. Andrews, I. Tsochantaridis, T. Hofmann","Support vector machines for multiple-instance learning","NeurIPS, 15, 2002",""),
(42,"W. J. Scheirer, A. de Rezende Rocha, A. Sapkota, T. E. Boult","Toward open set recognition","IEEE TPAMI, 35(7):1757-1772, 2013",""),
(43,"C. Geng, S.-j. Huang, S. Chen","Recent advances in open set recognition: A survey","IEEE TPAMI, 43(10):3614-3631, 2020",""),
(44,"W. Li, V. Mahadevan, N. Vasconcelos","Anomaly detection and localization in crowded scenes","IEEE TPAMI, 36(1):18-32, 2013",""),
(45,"W. Luo, W. Liu, S. Gao","A revisit of sparse coding based anomaly detection in stacked RNN framework","ICCV, 2017, pp. 341-349",""),
(46,"C. Cao, Y. Lu, P. Wang, Y. Zhang","A new comprehensive benchmark for semi-supervised video anomaly detection and anticipation","CVPR, 2023, pp. 20392-20401",""),
(47,"B. Ramachandra, M. Jones","Street scene: A new dataset and evaluation protocol for video anomaly detection","WACV, 2020, pp. 2569-2578",""),
(48,"F. Mumcu, M. Jones, Y. Yilmaz, A. Cherian","ComplexVAD: Detecting interaction anomalies in video","WACV, 2025, pp. 1093-1102",""),
(49,"H. I. Ozturk, A. B. Can","ADNet: Temporal anomaly detection in surveillance videos","ICPR, Springer, 2021, pp. 88-101",""),
(50,"P. Wu, J. Liu, Y. Shi, Y. Sun, F. Shao, Z. Wu, Z. Yang","Not only look, but also listen: Learning multimodal violence detection under weak supervision","ECCV, Springer, 2020, pp. 322-339",""),
(51,"Y. Xu, H. Hu, C. Huang, et al.","TAD: A large-scale benchmark for traffic accidents detection from video surveillance","IEEE Access, 13:2018-2033, 2024",""),
(52,"S. A. Velastin, D. A. Gomez-Lira","People detection and pose classification inside a moving train using computer vision","International Visual Informatics Conference, Springer, 2017, pp. 319-330",""),
(53,"D. D. de Paula, D. H. Salvadeo, D. M. de Araujo","CamNuvem: A robbery dataset for video anomaly detection","Sensors, 22(24):10016, 2022",""),
(54,"A. Acsintoae, A. Florescu, M.-I. Georgescu, et al.","UBnormal: New benchmark for supervised open-set video anomaly detection","CVPR, 2022, pp. 20143-20153",""),
(55,"L. Zhu, L. Wang, A. Raj, T. Gedeon, C. Chen","Advancing video anomaly detection: A concise review and a new dataset","NeurIPS, 37:89943-89977, 2024",""),
(56,"H. Du, S. Zhang, B. Xie, et al.","Uncovering what, why and how: A comprehensive benchmark for causation understanding of video anomaly","CVPR, 2024, pp. 18793-18803",""),
(57,"H. Du, G. Nan, J. Qian, et al.","Exploring what, why and how: A multifaceted benchmark for causation understanding of video anomaly","arXiv:2412.07183, 2024","https://arxiv.org/abs/2412.07183"),
(58,"H. Gani, R. Bharadwaj, M. Naseer, F. S. Khan, S. Khan","VANE-Bench: Video anomaly evaluation benchmark for conversational LMMs","Findings of ACL: NAACL, 2025, pp. 3123-3140",""),
(59,"S. Gao, P. Yang, Y. Liu, et al.","VAGU & GtS: LLM-based benchmark and framework for joint video anomaly grounding and understanding","AAAI, 40(6):4167-4175, 2026",""),
(60,"J. A. C. Pereira, V. Lopes, J. C. Neves, D. Semedo","FineVAU: A novel human-aligned benchmark for fine-grained video anomaly understanding","AAAI, 40(10):8403-8411, 2026",""),
(61,"H. Zhang, X. Xu, X. Wang, et al.","Holmes-VAU: Towards long-term video anomaly understanding at any granularity","CVPR, 2025, pp. 13843-13853",""),
(62,"T. Yuan, X. Zhang, K. Liu, et al.","Towards surveillance video-and-language understanding: New dataset, baselines and challenges","CVPR, 2024, pp. 22052-22061",""),
(63,"S. Yang, Y. Wang, Y. Wang, L. Zhu, Z. Zheng","Towards scalable video anomaly retrieval: A synthetic video-text benchmark","arXiv:2506.01466, 2025","https://arxiv.org/abs/2506.01466"),
(64,"Q. Bao, F. Liu, L. Jiao, et al.","Anomaly-led prompting learning caption generating model and benchmark","IEEE Trans. Multimedia, 2025",""),
(65,"N. T. Nguyen, L. Bekit, Y. Yilmaz","SENSE-VAD: Sentient and semantic video anomaly detection for autonomous driving","arXiv:2606.31875, 2026","https://arxiv.org/abs/2606.31875"),
(66,"T. Fawcett","An introduction to ROC analysis","Pattern Recognition Letters, 27(8):861-874, 2006",""),
(67,"J. Davis, M. Goadrich","The relationship between precision-recall and ROC curves","ICML, 2006, pp. 233-240",""),
(68,"M. Everingham, L. Van Gool, C. K. I. Williams, J. Winn, A. Zisserman","The PASCAL visual object classes (VOC) challenge","IJCV, 88(2):303-338, 2010",""),
(69,"K. Papineni, S. Roukos, T. Ward, W.-J. Zhu","BLEU: a method for automatic evaluation of machine translation","ACL, 2002, pp. 311-318",""),
(70,"C.-Y. Lin","ROUGE: A package for automatic evaluation of summaries","Text Summarization Branches Out, 2004, pp. 74-81",""),
(71,"S. Banerjee, A. Lavie","METEOR: An automatic metric for MT evaluation with improved correlation with human judgments","ACL Workshop on Intrinsic and Extrinsic Evaluation Measures, 2005, pp. 65-72",""),
(72,"F. Mumcu, M. J. Jones, A. Cherian, Y. Yilmaz","Leveraging multimodal LLM descriptions of activity for explainable semi-supervised video anomaly detection","arXiv:2510.14896, 2025","https://arxiv.org/abs/2510.14896"),
(73,"D. Gong, L. Liu, V. Le, et al.","Memorizing normality to detect anomaly: Memory-augmented deep autoencoder for unsupervised anomaly detection","ICCV, 2019, pp. 1705-1714",""),
(74,"M. M. Hemmatyar, M. Jafari, M. A. Yousefi, et al.","HyCoVAD: A hybrid SSL-LLM model for complex video anomaly detection","arXiv:2509.22544, 2025","https://arxiv.org/abs/2509.22544"),
(75,"Z. Ding, H. Zhang, P. Wu, et al.","SlowFastVAD: Video anomaly detection via integrating simple detector and RAG-enhanced vision-language model","arXiv:2504.10320, 2025","https://arxiv.org/abs/2504.10320"),
(76,"J. Li, L. Dang, Y. Su, et al.","MemoryOut: Learning principal features via multimodal sparse filtering network for semi-supervised video anomaly detection","arXiv:2506, 2025","https://arxiv.org/abs/2506"),
(77,"C. Li, Y. Jiang","VLAVAD: Vision-language models assisted unsupervised video anomaly detection","BMVC, 2024",""),
(78,"Y. Yang, K. Lee, B. Dariush, Y. Cao, S.-Y. Lo","Follow the rules: reasoning for video anomaly detection with large language models","ECCV, Springer, 2024, pp. 304-322",""),
(79,"Z. Liu, Y. Nie, C. Long, Q. Zhang, G. Li","A hybrid video anomaly detection framework via memory-augmented flow reconstruction and flow-guided frame prediction","ICCV, 2021, pp. 13588-13597",""),
(80,"J. Kim, S. Yoon, T. Choi, S. Sull","Unsupervised video anomaly detection based on similarity with predefined text descriptions","Sensors, 23(14):6256, 2023",""),
(81,"P. Wu, X. Zhou, G. Pang, et al.","VadCLIP: Adapting vision-language models for weakly supervised video anomaly detection","AAAI, 38(6):6074-6082, 2024",""),
(82,"S. Li, F. Liu, L. Jiao","Self-training multi-sequence learning with transformer for weakly supervised video anomaly detection","AAAI, 36(2):1395-1403, 2022",""),
(83,"J. Feng, F. Hong, W. Zheng","MIST: multiple instance self-training framework for video anomaly detection","arXiv:2104.01633, 2021","https://arxiv.org/abs/2104.01633"),
(84,"J.-X. Zhong, N. Li, W. Kong, S. Liu, T. H. Li, G. Li","Graph convolutional label noise cleaner: Train a plug-and-play action classifier for anomaly detection","CVPR, 2019, pp. 1237-1246",""),
(85,"J. Dalvi, A. Dabouei, G. Dhanuka, M. Xu","Distilling aggregated knowledge for weakly-supervised video anomaly detection","WACV, IEEE, 2025, pp. 5439-5448",""),
(86,"Y. Wang, S. Chen","Learning event completeness for weakly supervised video anomaly detection","arXiv:2506.13095, 2025","https://arxiv.org/abs/2506.13095"),
(87,"C. Huang, Y. Shi, J. Wen, W. Wang, Y. Xu, X. Cao","Ex-VAD: Explainable fine-grained video anomaly detection based on visual-language models","ICML, 2025",""),
(88,"B. Wang, C. Huang, J. Wen, W. Wang, Y. Liu, Y. Xu","Federated weakly supervised video anomaly detection with multimodal prompt","AAAI, 39(20):21017-21025, 2025",""),
(89,"H. Qiu, B. Hou, Y. Cui","Learning opposite prompts for weakly supervised video anomaly detection","Knowledge-Based Systems, 324:113600, 2025",""),
(90,"H. Qiu, B. Hou","Temporal context and representative feature learning for weakly supervised video anomaly detection","Journal of Information and Intelligence, 2025",""),
(91,"H. Xu, H. Wang, M. Yue, Z. Li","Filter, summarize, align: Learning the semantic guided weakly supervised video anomaly detection","International Conference on Intelligent Computing, Springer, 2025, pp. 76-87",""),
(92,"L. Liu, J. Li, G. Li, Y. Zhai, M. Zhang","VadCLIP++: Dynamic vision-language model for weakly supervised video anomaly detection","Digital Signal Processing, p. 105560, 2025",""),
(93,"J. Wang, G. Li, J. Liu, Z. Xu, X. Chen, J. Wei","RelVid: Relational learning with vision-language models for weakly video anomaly detection","Sensors, 25(7):2037, 2025",""),
(94,"P. Wu, W. Su, G. Pang, Y. Sun, Q. Yan, P. Wang, Y. Zhang","AVadCLIP: Audio-visual collaboration for robust video anomaly detection","arXiv:2504.04495, 2025","https://arxiv.org/abs/2504.04495"),
(95,"D. Wang, Q. Wang, Q. Hu, K. Wu","Multimodal VAD: Visual anomaly detection in intelligent monitoring system via audio-vision-language","IEEE Trans. Instrumentation and Measurement, 2025",""),
(96,"Y. Pu, X. Wu, L. Yang, S. Wang","Learning prompt-enhanced context features for weakly-supervised video anomaly detection","IEEE Trans. Image Processing, 33:4923-4936, 2024",""),
(97,"H. K. Joo, K. Vo, K. Yamazaki, N. Le","CLIP-TSA: CLIP-assisted temporal self-attention for weakly-supervised video anomaly detection","ICIP, IEEE, 2023, pp. 3230-3234",""),
(98,"P. P. Dev, R. Hazari, P. Das","ReFLIP-VAD: Towards weakly supervised video anomaly detection via vision-language model","IEEE Trans. Circuits and Systems for Video Technology, 2024",""),
(99,"W.-D. Jiang, C.-Y. Chang, H.-C. Chang, J.-Y. Chen, D. S. Roy","Injecting explainability and lightweight design into weakly supervised video anomaly detection systems","arXiv:2412.20201, 2024","https://arxiv.org/abs/2412.20201"),
(100,"H. Lim, D. Kim, M. Kim, C. Park, D. Kang, S. Lee","Weakly supervised video anomaly detection using dynamic-weighted feature fusion","ICCE-Asia, IEEE, 2024, pp. 1-4",""),
(101,"Z. Qian, J. Tan, Z. Ou, H. Wang","CLIP-driven multi-scale instance learning for weakly supervised video anomaly detection","ICME, IEEE, 2024, pp. 1-6",""),
(102,"S. Zhan, D. Zhang, J. Wang","Weakly supervised video anomaly detection with large language models knowledge enhancement framework","ICTAI, IEEE, 2024, pp. 468-475",""),
(103,"W. Chen, K. T. Ma, Z. J. Yew, M. Hur, D. A.-A. Khoo","TEVAD: Improved video anomaly detection with captions","CVPR, 2023, pp. 5549-5559",""),
(104,"Y. Tian, G. Pang, Y. Chen, R. Singh, J. W. Verjans, G. Carneiro","Weakly-supervised video anomaly detection with robust temporal feature magnitude learning","ICCV, 2021, pp. 4975-4986",""),
(105,"Y. Chen, Z. Liu, B. Zhang, W. Fok, X. Qi, Y.-C. Wu","MGFN: Magnitude-contrastive glance-and-focus network for weakly-supervised video anomaly detection","AAAI, 37(1):387-395, 2023",""),
(106,"M. Li, J. Sang, Y. Lu, L. Du","WSVAD-CLIP: Temporally aware and prompt learning with CLIP for weakly supervised video anomaly detection","Journal of Imaging, 11(10):354, 2025",""),
(107,"L. Zanella, B. Liberatori, W. Menapace, F. Poiesi, Y. Wang, E. Ricci","Delving into CLIP latent space for video anomaly recognition","CVIU, 249:104163, 2024",""),
(108,"P. Wu, X. Zhou, G. Pang, Z. Yang, Q. Yan, P. Wang, Y. Zhang","Weakly supervised video anomaly detection and localization with spatio-temporal prompts","ACM Multimedia, 2024, pp. 9301-9310",""),
(109,"J. Chen, L. Li, L. Su, Z.-j. Zha, Q. Huang","Prompt-enhanced multiple instance learning for weakly supervised video anomaly detection","CVPR, 2024, pp. 18319-18329",""),
(110,"C. Tao, X. Peng, C. Wang, et al.","Learning suspected anomalies from event prompts for video anomaly detection","ACM Trans. Multimedia Computing, Communications and Applications, 22(5):1-20, 2026",""),
(111,"C. Xiao, Y. Xiao, J. T. Zhou, Z. Fang","Multilingual-prompt-guided directional feature learning for weakly supervised video anomaly detection","IEEE TPAMI, 2025",""),
(112,"T. Liu, K.-M. Lam, B.-K. Bao","Injecting text clues for improving anomalous event detection from weakly labeled videos","IEEE Trans. Image Processing, 33:5907-5920, 2024",""),
(113,"A. Ntelopoulos, K. Nasrollahi","CALLM: Cascading autoencoder and large language model for video anomaly detection","IPTA, IEEE, 2024, pp. 1-6",""),
(114,"Y. Chen, J. Liu, R. Fan, et al.","Aligning effective tokens with video anomaly in large language models","ICCV, 2025, pp. 22695-22706",""),
(115,"G. Wang, S. Song, W. He, Y. Zheng","CMHKF: Cross-modality heterogeneous knowledge fusion for weakly supervised video anomaly detection","ACL, 2025, pp. 31594-31607",""),
(116,"S. Yun, R. Masukawa, M. Na, M. Imani","MissionGNN: Hierarchical multimodal GNN-based weakly supervised video anomaly recognition with mission-specific knowledge graph generation","WACV, IEEE, 2025, pp. 4736-4745",""),
(117,"P. Wu, J. Liu, X. He, Y. Peng, P. Wang, Y. Zhang","Toward video anomaly retrieval from video anomaly detection: New benchmarks and model","IEEE Trans. Image Processing, 33:2213-2225, 2024",""),
(118,"L. Zanella, W. Menapace, M. Mancini, Y. Wang, E. Ricci","Harnessing large language models for training-free video anomaly detection","CVPR, 2024, pp. 18527-18536",""),
(119,"P. Wu, X. Zhou, G. Pang, Y. Sun, J. Liu, P. Wang, Y. Zhang","Open-vocabulary video anomaly detection","CVPR, 2024, pp. 18297-18307",""),
(120,"F. Li, W. Liu, J. Chen, R. Zhang, Y. Wang, X. Zhong, Z. Wang","Anomize: Better open vocabulary video anomaly detection","CVPR, 2025, pp. 29203-29212",""),
(121,"C. Xu, K. Xu, X. Jiang, T. Sun","PLOVAD: Prompting vision-language models for open vocabulary video anomaly detection","IEEE Trans. Circuits and Systems for Video Technology, 35(6):5925-5938, 2025",""),
(122,"H. Zhang, X. Xu, X. Wang, et al.","Holmes-VAD: Towards unbiased and explainable video anomaly detection via multi-modal LLM","arXiv:2406.12235, 2024","https://arxiv.org/abs/2406.12235"),
(123,"L. Bekit, H. Karim, N. T. Nguyen, Y. Yilmaz","QVAD: A question-centric agentic framework for efficient and training-free video anomaly detection","arXiv:2604.03040, 2026","https://arxiv.org/abs/2604.03040"),
(124,"H. Lee, H. Kim, I.-J. Kim, Y. Choi","Flashback: Memory-driven zero-shot, real-time video anomaly detection","arXiv:2505.15205, 2025","https://arxiv.org/abs/2505.15205"),
(125,"M. Abdalla, S. Javed","Training-free VLM-based pseudo label generation for video anomaly detection","IEEE Access, 2025",""),
(126,"Y. Feng, Y. Liu, J. Zhang, J. Qin, et al.","MoniTor: Exploiting large language models with instruction for online video anomaly detection","NeurIPS, 38:35851-35871, 2026",""),
(127,"Y. Shao, H. He, S. Li, et al.","EventVAD: Training-free event-aware video anomaly detection","ACM Multimedia, 2025, pp. 2586-2595",""),
(128,"Z. Yang, C. Gao, M. Z. Shou","PANDA: Towards generalist video anomaly detection via agentic AI engineer","NeurIPS, 38:83182-83211, 2026",""),
(129,"W. Li, Y. Xu, Y. Rao, Z. Wang, S. Deng","VADTree: Explainable training-free video anomaly detection via hierarchical granularity-aware tree","NeurIPS, 38:148372-148404, 2026",""),
(130,"M. Ye, W. Liu, P. He","VERA: Explainable video anomaly detection via verbalized learning of vision-language models","CVPR, 2025, pp. 8679-8688",""),
(131,"S. Gao, P. Yang, L. Huang","SUVAD: Semantic understanding based video anomaly detection using MLLM","ICASSP, IEEE, 2025, pp. 1-5",""),
(132,"P. P. Dev, R. Hazari, P. Das","MCANet: Multimodal caption aware training-free video anomaly detection via large language model","ICPR, Springer, 2024, pp. 362-379",""),
(133,"S. Ahn, Y. Jo, K. Lee, S. Kwon, I. Hong, S. Park","AnyAnomaly: Zero-shot customizable video anomaly detection with LVLM","WACV, 2026, pp. 3026-3035",""),
(134,"J. Xu, S.-Y. Lo, B. Safaei, V. M. Patel, I. Dwivedi","Towards zero-shot anomaly detection and reasoning with multimodal large language models","CVPR, 2025, pp. 20370-20382",""),
(135,"Y. Cao, X. Xu, Y. Cheng, C. Sun, Z. Du, L. Gao, W. Shen","Personalizing vision-language models with hybrid prompts for zero-shot anomaly detection","IEEE Trans. Cybernetics, 2025",""),
(136,"M. Dong","CLIP: Assisted video anomaly detection","ICPRAM, 2024, pp. 522-533",""),
(137,"Y. Cao, X. Xu, C. Sun, X. Huang, W. Shen","Towards generic anomaly detection and understanding: Large-scale visual-linguistic model (GPT-4V) takes the lead","arXiv:2311.02782, 2023","https://arxiv.org/abs/2311.02782"),
(138,"H. Wang, J. Qin, A. Bastola, X. Chen, J. Suchanek, Z. Gong, A. Razi","VisionGPT: LLM-assisted real-time anomaly detection for safe visual navigation","arXiv:2403.12415, 2024","https://arxiv.org/abs/2403.12415"),
(139,"S. Lin, C. Wang, X. Ding, et al.","A VLM-based method for visual anomaly detection in robotic scientific laboratories","ICARM, IEEE, 2025, pp. 34-39",""),
(140,"J. Tang, H. Lu, R. Wu, et al.","HAWK: Learning to understand open-world video anomalies","NeurIPS, 37:139751-139785, 2024",""),
(141,"Z. Yang, C. Gao, J. Liu, P. Wu, G. Pang, M. Z. Shou","AssistPDA: An online video surveillance assistant for video anomaly prediction, detection, and analysis","arXiv:2503.21904, 2025","https://arxiv.org/abs/2503.21904"),
(142,"C. Huang, B. Wang, W. Wang, J. Wen, C. Liu, L. Shen, X. Cao","Vad-R1: Towards video anomaly reasoning via perception-to-cognition chain-of-thought","NeurIPS, 38:118486-118518, 2026",""),
(143,"L. Zhu, Q. Chen, X. Shen, X. Cun","VAU-R1: Advancing video anomaly understanding via reinforcement fine-tuning","arXiv:2505.23504, 2025","https://arxiv.org/abs/2505.23504"),
(144,"J. Ma, J. Wang, J. Luo, P. Yu, G. Zhou","Sherlock: Towards multi-scene video abnormal event extraction and localization via a global-local spatial-sensitive LLM","ACM Web Conference, 2025, pp. 4004-4013",""),
(145,"C. Huang, W. Huang, Q. Jiang, W. Wang, J. Wen, B. Zhang","Multimodal evidential learning for open-world weakly-supervised video anomaly detection","IEEE Trans. Multimedia, 2025",""),
(146,"Z. Liu, X. Wu, J. Wu, X. Wang, L. Yang","Language-guided open-world video anomaly detection under weak supervision","arXiv:2503.13160, 2025","https://arxiv.org/abs/2503.13160"),
(147,"F. Mumcu, M. J. Jones, A. Cherian, Y. Yilmaz","LLM-guided agentic object detection for open-world understanding","arXiv:2507.10844, 2025","https://arxiv.org/abs/2507.10844"),
(148,"G. Li, H. Hammoud, H. Itani, D. Khizbullin, B. Ghanem","CAMEL: Communicative agents for mind exploration of large language model society","NeurIPS, 36:51991-52008, 2023",""),
(149,"C. Qian, W. Liu, H. Liu, et al.","ChatDev: Communicative agents for software development","ACL, 2024, pp. 15174-15186",""),
(150,"G. Wang, Y. Xie, Y. Jiang, et al.","Voyager: An open-ended embodied agent with large language models","arXiv:2305.16291, 2023","https://arxiv.org/abs/2305.16291"),
(151,"N. Shinn, F. Cassano, A. Gopinath, K. Narasimhan, S. Yao","Reflexion: Language agents with verbal reinforcement learning","NeurIPS, 36:8634-8652, 2023",""),
(152,"P. Belcak, G. Heinrich, S. Diao, et al.","Small language models are the future of agentic AI","arXiv:2506.02153, 2025","https://arxiv.org/abs/2506.02153"),
(153,"F. Mumcu, Y. Yilmaz","Fast and lightweight vision-language model for adversarial traffic sign detection","Electronics, 13(11):2172, 2024",""),
(154,"A. Marafioti, O. Zohar, M. Farre, et al.","SmolVLM: Redefining small and efficient multimodal models","arXiv:2504.05299, 2025","https://arxiv.org/abs/2504.05299"),
(155,"Nvidia","How small language models are key to scalable agentic AI","NVIDIA Developer Blog, 2025","https://developer.nvidia.com/blog/how-small-language-models-are-key-to-scalable-agentic-ai/"),
(156,"A. Kamath, J. Ferret, S. Pathak, et al.","Gemma 3 technical report","arXiv:2503.19786, 2025","https://arxiv.org/abs/2503.19786"),
(157,"G. Team, A. Kamath, J. Ferret, et al.","Gemma 3 technical report","arXiv:2503.19786, 2025","https://arxiv.org/abs/2503.19786"),
(158,"A. Yang, A. Li, B. Yang, et al.","Qwen3 technical report","arXiv:2505.09388, 2025","https://arxiv.org/abs/2505.09388"),
(159,"J. Xu, Z. Guo, H. Hu, et al.","Qwen3-omni technical report","arXiv:2509.17765, 2025","https://arxiv.org/abs/2509.17765"),
(160,"Q. Team","Qwen3.5-omni technical report","arXiv:2604.15804, 2026","https://arxiv.org/abs/2604.15804"),
(161,"F. Mumcu, M. J. Jones, A. Cherian, Y. Yilmaz","Is video anomaly detection misframed? Evidence from LLM-based and multi-scene models","arXiv:2605.12725, 2026","https://arxiv.org/abs/2605.12725"),
(162,"F. Mumcu, Y. Yilmaz","Socially-weighted alignment: A game-theoretic framework for multi-agent LLM systems","arXiv:2602.14471, 2026","https://arxiv.org/abs/2602.14471"),
(163,"M. Abou Ali, F. Dornaika, J. Charafeddine","Agentic AI: a comprehensive survey of architectures, applications, and future directions","Artificial Intelligence Review, 59(1):11, 2025",""),
(164,"F. Mumcu, Y. Yilmaz","Robustness of agentic AI systems via adversarially-aligned Jacobian regularization","arXiv:2603.04378, 2026","https://arxiv.org/abs/2603.04378"),
(165,"F. Mumcu, K. Doshi, Y. Yilmaz","Adversarial machine learning attacks against video anomaly detection systems","CVPR Workshops, 2022, pp. 206-213",""),
(166,"M. Nafez, M. Poulaei, N. Vasei, M. Sabokrou, M. H. Rohban, et al.","FrameShield: Adversarially robust video anomaly detection","NeurIPS, 38:29859-29893, 2026",""),
(167,"OpenAI","Introducing GPT-5.5","openai.com, 2026, accessed July 14, 2026","https://openai.com/index/introducing-gpt-5-5/"),
]

refs = [{"id":i, "key":f"ref{i}", "title":t, "authors":a, "venue":v,
         "url": u if u else "#"} for (i,a,t,v,u) in R]
with open(os.path.join(ROOT,"data/references.json"),"w") as f:
    json.dump(refs, f, indent=1, ensure_ascii=False)
print(f"references.json: {len(refs)} references (ids {refs[0]['id']}-{refs[-1]['id']})")
