import { readFile, writeFile, mkdir, rm, cp, readdir } from 'node:fs/promises';
import path from 'node:path';
import katex from 'katex';

const root = process.cwd();
const out = path.join(root, 'dist');
const readJson = async (p) => JSON.parse(await readFile(path.join(root, p), 'utf8'));
const [stats, papers, datasets, benchmarks, versions, refs] = await Promise.all([
  readJson('data/statistics.json'), readJson('data/papers.json'), readJson('data/datasets.json'),
  readJson('data/benchmarks.json'), readJson('data/versions.json'), readJson('data/references.json')
]);
const currentVersion=versions.find(v=>v.version===stats.version)||versions.find(v=>v.status==='Current')||versions[0];
const releaseFolders=(await readdir(path.join(root,'versions'),{withFileTypes:true})).filter(x=>x.isDirectory()).map(x=>x.name);
const frozenVersionNames=(await Promise.all(releaseFolders.map(async version=>{try{await readJson(`versions/${version}/release.json`);return version}catch(error){if(error.code==='ENOENT')return null;throw error}}))).filter(Boolean).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
async function listMarkdownFiles(directory,prefix=''){const files=[];for(const entry of await readdir(directory,{withFileTypes:true})){const relative=path.join(prefix,entry.name);if(entry.isDirectory())files.push(...await listMarkdownFiles(path.join(directory,entry.name),relative));else if(entry.name.endsWith('.md'))files.push(relative)}return files}
const frozenReleases=Object.fromEntries(await Promise.all(frozenVersionNames.map(async version=>[version,{
  release:await readJson(`versions/${version}/release.json`),stats:await readJson(`versions/${version}/data/statistics.json`),papers:await readJson(`versions/${version}/data/papers.json`),datasets:await readJson(`versions/${version}/data/datasets.json`),benchmarks:await readJson(`versions/${version}/data/benchmarks.json`),refs:await readJson(`versions/${version}/data/references.json`),contentFiles:await listMarkdownFiles(path.join(root,`versions/${version}/content`)),root:`versions/${version}`
}])));
const diffFiles=(await readdir(path.join(root,'data/diffs'))).filter(x=>x.endsWith('.json')).sort();
const diffs=Object.fromEntries(await Promise.all(diffFiles.map(async f=>{const d=await readJson(`data/diffs/${f}`);return [`${d.from}--${d.to}`,d]})));

const sections = [
  ['introduction','Introduction','content/introduction.md'],
  ['problem-settings','Problem Settings and Supervision','content/problem-settings.md'],
  ['datasets','Datasets','content/datasets.md'],
  ['evaluation','Evaluation Metrics','content/evaluation.md'],
  ['methods/semi-supervised','Unsupervised and Semi-Supervised','content/methods/semi-supervised.md'],
  ['methods/weakly-supervised','Weakly Supervised','content/methods/weakly-supervised.md'],
  ['methods/training-free','Training-Free','content/methods/training-free.md'],
  ['methods/instruction-tuned','Instruction-Tuned','content/methods/instruction-tuned.md'],
  ['methods/open-world','Open-World and Open-Vocabulary','content/methods/open-world.md'],
  ['maintenance','Dynamic Survey Maintenance','content/maintenance.md'],
  ['challenges','Challenges and Future Directions','content/challenges.md'],
  ['survey-scope','Survey Scope and Literature Collection','content/survey-scope.md'],
  ['conclusion','Conclusion','content/conclusion.md'],
  ['appendix','Appendix: Reproducibility Characteristics','content/reproducibility-appendix.md']
];

const escapeHtml = (s='') => String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const slugify = s => s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const isTableRow = (l='') => l.trim().startsWith('|') && l.trim().endsWith('|');
const isTableRule = (l='') => /^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)+\|?\s*$/.test(l);
const splitRow = (l) => l.trim().replace(/^\|/,'').replace(/\|$/,'').split('|').map(c=>c.trim());
function renderTable(headerLine, bodyLines, options={}) {
  const head = splitRow(headerLine);
  const rows = bodyLines.map(splitRow);
  return `<div class="table-wrap"><table><thead><tr>${head.map(c=>`<th>${inline(c,options)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${inline(c,options)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
function renderMath(src, displayMode) {
  try {
    return katex.renderToString(src.trim(), { throwOnError: false, displayMode, output: 'html' });
  } catch (e) {
    return `<span class="math-error">${escapeHtml(src)}</span>`;
  }
}
function markdown(md, options={}) {
  const lines = md.trim().split(/\n/); let html = '', para = [];
  const flush = () => { if (para.length) { html += `<p>${inline(para.join(' '),options)}</p>`; para=[]; } };
  for (let i=0;i<lines.length;i++) {
    const line = lines[i];
    if (!line.trim()) { flush(); continue; }
    if (line.startsWith('$$')) { flush(); html += `<div class="equation" role="math">${renderMath(line.replace(/^\$\$|\$\$$/g,''), true)}</div>`; continue; }
    const h = line.match(/^(#{1,3})\s+(.+)/);
    if (h) { flush(); const level=h[1].length, id=slugify(h[2]); html += `<h${level} id="${id}">${inline(h[2],options)}<a class="anchor" href="#${id}" aria-label="Link to this heading">#</a></h${level}>`; continue; }
    if (isTableRow(line) && lines[i+1] && isTableRule(lines[i+1])) {
      flush();
      const body = [];
      let j = i+2;
      while (j<lines.length && isTableRow(lines[j])) { body.push(lines[j]); j++; }
      html += renderTable(line, body, options);
      i = j-1;
      continue;
    }
    const fig = line.match(/^!\[(.*)\]\((.*)\)$/);
    if (fig) { flush(); html += `<figure class="paper-figure"><img src="${options.figureBase||'/assets/figures'}/${fig[2]}" alt="${escapeHtml(fig[1])}" loading="lazy"><figcaption>${inline(fig[1],options)}</figcaption></figure>`; continue; }
    para.push(line);
  }
  flush(); return html;
}
function inline(s, options={}) {
  const mathTokens = [];
  const withoutMath = s.replace(/\$([^$]+?)\$/g, (_, expr) => {
    const token = `\x01${mathTokens.length}\x02`;
    mathTokens.push(renderMath(expr, false));
    return token;
  });
  let html = escapeHtml(withoutMath)
    .replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
    .replace(/\[(\d+)\]/g,(_,n)=>`<a class="citation" href="${options.citationBase||'/survey/full/'}#ref-${n}" title="View reference">[${n}]</a>`);
  html = html.replace(/\x01(\d+)\x02/g, (_, i) => mathTokens[Number(i)]);
  return html;
}
const nav = [
 ['Home','/'],['Survey','/survey/'],['Explore','/explore/'],['Datasets','/datasets/'],
 ['Benchmarks','/benchmarks/'],['Updates','/updates/'],['Maintenance','/maintenance/'],['About','/about/']
];
const rootPrefixScript = `<script>const projectHost=location.hostname.endsWith('github.io')&&location.hostname!=='dynamicvadsurvey.github.io';const segment=projectHost?location.pathname.split('/')[1]:'';document.documentElement.dataset.base=segment?'/'+segment+'/':'/'</script>`;
const href = p => p;
function shell({title, description, active='', body, extra=''}) {
  const links=nav.map(([label,url])=>`<a href="${href(url)}" ${active===label?'aria-current="page"':''}>${label}</a>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} — Dynamic VAD Survey</title><meta name="description" content="${escapeHtml(description)}"><meta name="theme-color" content="#17324d"><meta property="og:title" content="${escapeHtml(title)} — Dynamic VAD Survey"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/assets/katex.min.css"><link rel="stylesheet" href="/assets/site.css"><script defer src="https://cloud.umami.is/script.js" data-website-id="880d43d0-e2c5-4144-87b2-abaded14db07"></script>${rootPrefixScript}</head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="/"><span class="brand-mark">DV</span><span>Dynamic VAD Survey<small>Living scholarly resource</small></span></a><button class="menu-button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav id="site-nav" aria-label="Primary">${links}<a class="pdf-button" href="/survey/full/" title="Sample web snapshot; archival PDF not yet supplied">Read Survey PDF*</a></nav></div></header><main id="main">${body}</main>
<footer><div><strong>Dynamic VAD Survey</strong><p>A continuously maintained, human-reviewed survey companion.</p><div class="site-credit"><p>Website designed and maintained by Furkan Mumcu. <span class="contact-links"><a href="mailto:furkan@usf.edu" aria-label="Email Furkan Mumcu" title="Email Furkan Mumcu"><svg class="contact-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M1.5 3h13A1.5 1.5 0 0 1 16 4.5v7a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 11.5v-7A1.5 1.5 0 0 1 1.5 3Zm0 1a.5.5 0 0 0-.5.5v.243l7 4.2 7-4.2V4.5a.5.5 0 0 0-.5-.5h-13ZM15 5.91 8.257 9.956a.5.5 0 0 1-.514 0L1 5.91v5.59a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5V5.91Z"/></svg></a><a href="https://github.com/dynamicVADsurvey/dynamicVADsurvey.github.io/issues/new" aria-label="Open a GitHub issue" title="Open a GitHub issue"><svg class="contact-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M8 0C3.58 0 0 3.64 0 8.13c0 3.59 2.29 6.64 5.47 7.72.4.08.55-.18.55-.39 0-.19-.01-.84-.01-1.52-2.01.38-2.53-.5-2.69-.96-.09-.23-.48-.96-.82-1.15-.28-.15-.68-.53-.01-.54.63-.01 1.08.59 1.23.83.72 1.23 1.87.88 2.33.67.07-.53.28-.88.51-1.08-1.78-.21-3.64-.91-3.64-4.02 0-.89.31-1.62.82-2.19-.08-.21-.36-1.04.08-2.16 0 0 .67-.22 2.2.84A7.5 7.5 0 0 1 8 3.9c.68 0 1.36.09 2 .27 1.53-1.06 2.2-.84 2.2-.84.44 1.12.16 1.95.08 2.16.51.57.82 1.3.82 2.19 0 3.12-1.87 3.81-3.65 4.02.29.25.54.74.54 1.5 0 1.08-.01 1.95-.01 2.22 0 .22.15.47.55.39A8.15 8.15 0 0 0 16 8.13C16 3.64 12.42 0 8 0Z"/></svg></a></span></p></div></div><nav class="footer-links" aria-label="Footer"><a href="/">Home</a><a href="/survey/">Survey</a><a href="/explore/">Explore</a><a href="/datasets/">Datasets</a><a href="/benchmarks/">Benchmarks</a><a href="/updates/">Updates</a><a href="/maintenance/">Maintenance</a><a href="/about/">About</a></nav><p class="fine-print">* Archival PDF not supplied; the PDF action opens the printable full-document sample.</p></footer>
<script src="/assets/site.js" defer></script>${extra}</body></html>`;
}
function badge(s, cls='') { return `<span class="badge ${cls}">${escapeHtml(s)}</span>`; }
function home() {
 const statItems=[['Papers',stats.papers],['Datasets',datasets.length],['Paradigms',new Set(papers.map(p=>p.paradigm)).size],['Current Version',stats.version],['Last Updated',stats.lastUpdated]].map(([k,v])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('');
 const citation=`@article{mumcu2026dynamicvad,\n  title={Language Models in Video Anomaly Detection: A Dynamic Survey},\n  author={Mumcu, Furkan and Bekit, Lokman and Jones, Michael J. and Cherian, Anoop and Yilmaz, Yasin},\n  journal={IEEE Access},\n  year={2026},\n  version={${stats.version}},\n  url={https://dynamicvadsurvey.github.io/},\n  note={Website version ${stats.version}, accessed __ACCESS_DATE__}\n}`;
 return shell({title:'Language Models in Video Anomaly Detection',description:'A continuously maintained survey of language-model-based video anomaly detection.',active:'Home',body:`<section class="hero"><div class="eyebrow">A dynamic survey · ${stats.version}</div><h1>Language Models in<br><em>Video Anomaly Detection</em></h1><p>A continuously maintained, agentic-AI-assisted survey covering methods, datasets, benchmarks, evaluation protocols, and emerging research directions, with human-reviewed releases.</p><div class="actions"><a class="button primary" href="/survey/">Explore the Survey</a><a class="button" href="/explore/">Browse Methods</a><a class="text-action" href="/updates/">View latest updates →</a></div></section><section class="status-strip" aria-label="Project status">${statItems}</section><section class="citation-home"><div><div class="section-label">How to cite this resource</div><h2>Cite the paper.<br>Reference the version.</h2><p>Use the archival paper’s standard BibTeX citation. The maintained website version, URL, and access date are included as additional fields in that same entry.</p><a href="/about/">Full citation guidance →</a></div><div class="citation-example"><div class="citation-example-head"><span>Extended paper BibTeX</span><button class="copy-citation" data-copy="${escapeHtml(citation)}">Copy BibTeX</button></div><pre><code data-dynamic-bibtex>${escapeHtml(citation)}</code></pre><p>Replace the clearly marked author, venue, and archival metadata once the final paper citation is supplied.</p></div></section><section class="changes"><div><div class="section-label">Current release · Version 1.0</div><h2>Initial public release</h2></div><div class="change-counts"><span><b>${papers.length}</b> structured methods</span><span><b>${datasets.length}</b> datasets</span><span><b>${benchmarks.length}</b> benchmark rows</span><span><b>${refs.length}</b> references</span></div><a class="button inverse" href="/updates/">View release details</a></section><section class="workflow-home"><div><div class="section-label">Transparent maintenance</div><h2>Assisted by agents.<br>Released by humans.</h2><p>Agentic tools assist with discovery, summarization, routing, and localized updates. Public releases remain human-reviewed and versioned.</p></div><ol>${['Paper discovery','Relevance screening','Technical extraction','Taxonomy routing','Human review','Versioned release'].map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${x}</li>`).join('')}</ol></section>`});
}
function surveyPage(index, html, full=false, context={}) {
 const pageSections=context.sections||sections,version=context.version||stats.version,versionStats=context.stats||stats,routeBase=context.routeBase||'/survey';
 const [,title]=pageSections[index]||['','Full Survey'];
 const sectionPath=full?'full':pageSections[index][0];
 const toc=pageSections.map(([slug,label],i)=>`<a href="${routeBase}/${slug}/"><span>${i+1}</span>${label}</a>`).join('');
 const headings=[...html.matchAll(/<h([23]) id="([^"]+)">([^<]+)/g)].map(m=>`<a href="#${m[2]}" class="depth-${m[1]}">${m[3]}</a>`).join('');
 const previous=index>0?pageSections[index-1]:null,next=index<pageSections.length-1?pageSections[index+1]:null;
 const available=[{...currentVersion,kind:'latest'},...frozenVersionNames.map(v=>({...((versions.find(x=>x.version===v)||frozenReleases[v].release)),kind:'archive'}))];
 const definition=sections.find(([slug])=>slug===sectionPath),relativeSource=definition?.[2].replace(/^content\//,'');
 const versionOptions=available.map(v=>{let target;if(v.kind==='latest')target=`/survey/${sectionPath}/`;else{const hasSection=full||!relativeSource||frozenReleases[v.version]?.contentFiles.includes(relativeSource);target=hasSection?`/versions/${v.version}/survey/${sectionPath}/`:`/versions/${v.version}/survey/`}const selected=routeBase==='/survey'?v.kind==='latest':v.kind==='archive'&&v.version===version;const label=v.kind==='latest'?`Latest survey (${v.version})`:`${v.version} — Frozen archive`;return `<option value="${target}" ${selected?'selected':''}>${label}</option>`}).join('');
 return shell({title:full?'Full Survey':title,description:`Web-native survey section: ${title}.`,active:'Survey',body:`<div class="survey-layout"><aside class="survey-toc"><div class="aside-title">Survey contents</div><nav>${toc}<a class="full-link" href="${routeBase}/full/">Full document mode</a></nav><div class="version-select"><label for="survey-version">Reading version</label><select id="survey-version">${versionOptions}</select><small>v1.1 is planned and will appear here when released. If a section is absent from an older release, selecting it opens that release's full survey.</small></div></aside><article class="survey-article"><div class="version-bar"><span><b>Survey Version</b>${version}</span><span><b>Last Updated</b>${versionStats.lastUpdatedFull}</span><span><b>Last Changed In</b>${version}</span></div>${html}${!full?`<nav class="page-turn">${previous?`<a href="${routeBase}/${previous[0]}/">← <small>Previous</small>${previous[1]}</a>`:'<span></span>'}${next?`<a class="next" href="${routeBase}/${next[0]}/"><small>Next</small>${next[1]} →</a>`:'<span></span>'}</nav>`:''}</article><aside class="on-page"><details open><summary>On this page</summary><nav>${headings||'<span>Full document</span>'}</nav></details><a class="related-card" href="/explore/"><small>Related resource</small>Browse structured method records →</a></aside></div>`});
}
function paperRows() { return papers.map(p=>`<tr data-record data-search="${escapeHtml([p.method,p.title,p.authors.join(' '),p.venue,p.datasets.join(' '),p.modelTypes.join(' '),p.tasks.join(' ')].join(' ').toLowerCase())}" data-paradigm="${escapeHtml(p.paradigm)}" data-model="${escapeHtml(p.modelTypes.join('|'))}" data-training="${escapeHtml(p.training)}"><td><a href="/papers/${p.slug}/"><strong>${escapeHtml(p.method)}</strong><small>${escapeHtml(p.title)}</small></a></td><td>${p.year}</td><td>${badge(p.paradigm)}</td><td>${p.modelTypes.map(x=>badge(x,'neutral')).join('')}</td><td>${p.tasks.slice(0,3).join(', ')}</td><td>${p.code?'Yes':'—'}</td></tr>`).join(''); }
function paperCards() { return papers.map(p=>`<article class="paper-card" data-record data-search="${escapeHtml(JSON.stringify(p).toLowerCase())}" data-paradigm="${escapeHtml(p.paradigm)}" data-model="${escapeHtml(p.modelTypes.join('|'))}" data-training="${escapeHtml(p.training)}"><div>${badge(p.paradigm)} ${badge(String(p.year),'neutral')}</div><h3><a href="/papers/${p.slug}/">${escapeHtml(p.method)}</a></h3><h4>${escapeHtml(p.title)}</h4><p>${escapeHtml(p.summary)}</p><div class="card-meta"><span>${escapeHtml(p.venue)} ${p.year}</span><span>${p.code?'Code listed':'No code listed'}</span></div></article>`).join(''); }
function explorer() {
 const opts=(arr)=>[...new Set(arr)].sort().map(x=>`<option>${escapeHtml(x)}</option>`).join('');
 return shell({title:'Explore the Literature',description:'Search and filter language-model-based VAD papers and methods.',active:'Explore',body:`<header class="page-hero"><div class="section-label">Structured literature explorer</div><h1>Find methods by the question you are asking.</h1><p>Search representative records by title, method, dataset, model, task, author, or venue.</p></header><section class="explorer-shell"><aside class="filters"><div class="filter-heading"><h2>Filters</h2><button id="clear-filters" class="link-button">Clear all</button></div><label>Paradigm<select id="filter-paradigm"><option value="">All paradigms</option>${opts(papers.map(p=>p.paradigm))}</select></label><label>Model type<select id="filter-model"><option value="">All model types</option>${opts(papers.flatMap(p=>p.modelTypes))}</select></label><label>Training<select id="filter-training"><option value="">All training</option>${opts(papers.map(p=>p.training))}</select></label><div class="filter-note"><strong>Sample corpus</strong><p>${papers.length} representative records demonstrate the interface; the status count reflects the target reviewed corpus.</p></div></aside><div class="results"><div class="search-row"><label class="search"><span class="sr-only">Search papers</span><input id="paper-search" type="search" placeholder="Search papers, methods, datasets, models, or tasks…"></label><div class="view-toggle" role="group" aria-label="Display style"><button class="active" data-view="table" aria-pressed="true">Table</button><button data-view="cards" aria-pressed="false">Cards</button></div></div><div class="result-summary"><span><strong id="result-count">${papers.length}</strong> sample methods</span><span>Sorted by year, newest first</span></div><div id="table-view" class="table-wrap"><table><thead><tr><th>Method</th><th>Year</th><th>Paradigm</th><th>Model</th><th>Tasks</th><th>Code</th></tr></thead><tbody>${paperRows()}</tbody></table></div><div id="card-view" class="paper-grid" hidden>${paperCards()}</div><div id="no-results" class="empty-state" hidden><h3>No matching methods</h3><p>Try clearing one or more filters.</p></div></div></section>`});
}
function paperPage(p) { const links=[['Paper',p.paperUrl],p.codeUrl?['Code',p.codeUrl]:null,['Survey section',`/survey/${p.paradigm==='Training-Free'?'methods/training-free':'introduction'}/`]].filter(Boolean); return shell({title:p.method,description:p.title,active:'Explore',body:`<article class="detail-page"><a class="back" href="/explore/">← Back to literature explorer</a><header class="paper-header"><div>${badge(p.paradigm)} ${badge(p.status,'warning')}</div><h1>${escapeHtml(p.method)}</h1><p>${escapeHtml(p.title)}</p><span>${escapeHtml(p.venue)} · ${p.year}</span></header><div class="detail-grid"><div><section><div class="section-label">Human-reviewed summary status</div><h2>Survey summary</h2><p>${escapeHtml(p.summary)}</p></section><section><div class="section-label">Taxonomy placement</div><h2>${escapeHtml(p.taxonomy.split(' / ')[0])}</h2><div class="taxonomy-path">${p.taxonomy.split(' / ').map((x,i)=>`<span style="--i:${i}">${escapeHtml(x)}</span>`).join('')}</div></section><section><div class="section-label">Method characteristics</div><div class="badge-cloud">${[p.paradigm,...p.badges].map(x=>badge(x)).join('')}</div></section></div><aside class="metadata-card"><h2>Metadata</h2>${[['Model types',p.modelTypes.join(', ')],['Training',p.training],['Tasks',p.tasks.join(', ')],['Datasets',p.datasets.join(', ')],['Authors',p.authors.join(', ')]].map(([k,v])=>`<div><dt>${k}</dt><dd>${escapeHtml(v)}</dd></div>`).join('')}<div class="resource-links">${links.map(([k,u])=>`<a href="${u}">${k} →</a>`).join('')}</div><h3>Version history</h3><dl><div><dt>Added in</dt><dd>${p.added}</dd></div><div><dt>Last updated</dt><dd>${p.updated}</dd></div><div><dt>Last verified</dt><dd>${p.verified}</dd></div></dl></aside></div></article>`}); }
function datasetsPage(){ const groups=[...new Set(datasets.map(d=>d.group))]; return shell({title:'Datasets',description:'Interactive dataset metadata for video anomaly detection.',active:'Datasets',body:`<header class="page-hero"><div class="section-label">Evidence catalog</div><h1>Datasets shape what anomaly systems can claim.</h1><p>Filter representative records by annotation and task. Every row carries a verification note.</p></header><section class="data-page"><div class="dataset-groups">${groups.map(g=>`<button data-dataset-group="${g}"><span>${datasets.filter(d=>d.group===g).length}</span>${g}</button>`).join('')}</div><div class="table-tools"><input id="dataset-search" type="search" placeholder="Search datasets or annotations…"><button id="dataset-clear" class="button small">Show all</button></div><div class="table-wrap"><table class="dataset-table"><thead><tr><th>Dataset</th><th>Year / domain</th><th>Scale</th><th>Temporal</th><th>Spatial</th><th>Semantic</th><th>Tasks</th></tr></thead><tbody>${datasets.map(d=>`<tr data-dataset data-group="${d.group}" data-search="${escapeHtml(JSON.stringify(d).toLowerCase())}"><td><strong>${d.name}</strong><small>${badge(d.group,'neutral')}<br>${d.verified}</small></td><td>${d.year}<small>${d.domain}</small></td><td>${d.scale}</td><td>${d.temporal}</td><td>${d.spatial}</td><td>${d.semantic}</td><td>${d.tasks.join(', ')}</td></tr>`).join('')}</tbody></table></div></section>`}); }
function benchmarksPage(){ return shell({title:'Benchmarks',description:'Protocol-aware benchmark comparison tables.',active:'Benchmarks',body:`<header class="page-hero"><div class="section-label">Protocol before rank</div><h1>Comparison tables with their caveats attached.</h1><p>Representative values show source, protocol, verification, and comparability rather than implying a universal leaderboard.</p></header><section class="data-page"><div class="notice"><strong>Do not compare blindly.</strong><span>Rows may use different protocols. Reliability labels describe evidence, not method quality.</span></div>${[...new Set(benchmarks.map(b=>b.group))].map(g=>`<section class="benchmark-group"><h2>${g}</h2><div class="table-wrap"><table><thead><tr><th>Method</th><th>Dataset</th><th>Metric</th><th>Value</th><th>Protocol</th><th>Reliability</th></tr></thead><tbody>${benchmarks.filter(b=>b.group===g).map((b,i)=>`<tr><td>${b.method}</td><td>${b.dataset}</td><td>${b.metric}</td><td><button class="value-button" data-dialog="benchmark-${slugify(g)}-${i}">${b.value}</button><dialog id="benchmark-${slugify(g)}-${i}"><button class="dialog-close" aria-label="Close">×</button><h3>${b.method}</h3><p><strong>${b.dataset} ${b.metric}: ${b.value}</strong></p><dl><div><dt>Source</dt><dd>${b.source}</dd></div><div><dt>Added in</dt><dd>v1.0</dd></div>${b.previous?`<div><dt>Previous value</dt><dd>${b.previous}</dd></div><div><dt>Corrected in</dt><dd>${b.corrected}</dd></div>`:''}</dl></dialog></td><td>${b.protocol}<small>${b.comparable?'Comparable within stated sample':'Not directly comparable'}</small></td><td>${badge(b.reliability,b.reliability.includes('Unclear')?'warning':'')}</td></tr>`).join('')}</tbody></table></div></section>`).join('')}</section>`}); }
function updatesPage(){const planned=versions.find(v=>v.status==='Planned');return shell({title:'Updates',description:'Changelog and version history for the maintained survey.',active:'Updates',body:`<header class="page-hero"><div class="section-label">Editorial record</div><h1>Every public change gets a reason and a version.</h1><p>Version ${currentVersion.version} is the initial public release. ${planned?.version||'The next version'} is reserved for the next human-reviewed update.</p><div class="actions"><a class="button primary" href="/updates/compare/">Version comparisons</a><a class="button" href="#history">Version history</a></div></header><section class="updates-layout"><article><div class="release-kicker"><span>Current release</span><time>${currentVersion.date}</time></div><h2>${currentVersion.version} — ${currentVersion.title}</h2><div class="changelog-grid"><div><h3>+ Published</h3><ul><li>Web-native survey sections</li><li>Structured method and dataset records</li><li>Protocol-aware benchmark tables</li></ul></div><div><h3>+ Versioned</h3><ul><li>Complete immutable v1.0 archive</li><li>Public release metadata</li><li>Static GitHub Pages build</li></ul></div><div><h3>✓ Reviewed</h3><p>Public content remains subject to the verification notes shown throughout the site.</p></div><div><h3>→ Next</h3><p>${planned?.version||'v1.1'} remains a placeholder until its human-reviewed frozen release is created.</p></div></div></article><aside><h2>Release metadata</h2><dl><div><dt>Git tag</dt><dd>${currentVersion.tag}</dd></div><div><dt>Status</dt><dd>${badge(currentVersion.status)}</dd></div><div><dt>Snapshot</dt><dd><a href="/versions/${currentVersion.version}/">Open ${currentVersion.version}</a></dd></div></dl></aside></section><section id="history" class="history"><div class="section-label">Release roadmap</div><h2>Version history</h2>${versions.map(v=>`<article><div><span class="version-dot"></span><time>${v.date}</time></div><div><h3>${v.version} · ${v.title}</h3><p>${v.summary}</p>${v.status==='Planned'?'<span>Snapshot available after release</span>':`<span>${v.tag}</span> · <a href="/versions/${v.version}/">Open snapshot →</a>`}</div><div>${badge(v.status,v.status==='Planned'?'neutral':'')}</div></article>`).join('')}</section>`});}
function comparePage(){const initial=Object.values(diffs)[0];if(!initial)return shell({title:'Compare Versions',description:'Version comparison availability.',active:'Updates',body:`<header class="page-hero compact"><div class="section-label">Version transparency</div><h1>Compare survey versions</h1><p>Comparisons will become available when v1.1 is released with a human-reviewed frozen archive.</p></header><section class="data-page"><div class="notice"><strong>One published version</strong><span>v1.0 is currently the only complete frozen release, so there is no earlier or later snapshot to compare yet.</span></div></section>`});const versionOptions=frozenVersionNames.map(v=>`<option value="${v}">${v}</option>`).join('');return shell({title:'Compare Versions',description:'Unified semantic diff between survey releases.',active:'Updates',body:`<header class="page-hero compact"><div class="section-label">Version transparency</div><h1>Compare survey versions</h1><p>All comparisons below are generated from complete frozen releases.</p></header><section class="compare-controls"><label>From<select id="diff-from">${versionOptions}</select></label><span>→</span><label>To<select id="diff-to">${versionOptions}</select></label><button id="compare-submit" class="button primary">Compare versions</button></section><div id="compare-error" class="empty-state" hidden></div><section id="diff-summary" class="diff-summary"></section><section id="diff-panel" class="diff-panel" data-view="unified"><div class="diff-toolbar"><div role="group" aria-label="Comparison display"><button class="active" data-diff-view="unified" aria-pressed="true">Unified</button><button data-diff-view="side" aria-pressed="false">Side-by-side</button><button data-diff-view="summary" aria-pressed="false">Summary only</button></div><label>Section<select id="diff-section"><option value="">All sections</option></select></label></div><div class="side-headings" aria-hidden="true"><span>Earlier version</span><span>Later version</span></div><div id="diff-list"></div></section><script id="version-diffs" type="application/json">${JSON.stringify(diffs).replace(/</g,'\\u003c')}</script><script>document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#diff-from').value='${initial.from}';document.querySelector('#diff-to').value='${initial.to}';document.querySelector('#compare-submit').click()})</script>`});}
function versionLandingPage(v){const r=v.release;return shell({title:`Survey Snapshot ${r.version}`,description:`Frozen release snapshot for ${r.version}.`,active:'Updates',body:`<header class="page-hero compact"><div class="section-label">Frozen version snapshot</div><h1>${r.version}</h1><p>Released ${r.date} · Git tag ${r.tag} · ${r.status}</p><div class="actions"><a class="button primary" href="/versions/${r.version}/survey/">Read the frozen survey</a><a class="button" href="/updates/">Version history</a></div></header><section class="snapshot-grid"><article><h2>Complete release archive</h2><p>This release is generated only from the frozen files under <code>versions/${r.version}/</code>. Later edits to the live survey do not change it.</p><p>${escapeHtml(r.summary)}</p></article><aside><h2>Frozen records</h2><p><strong>${v.papers.length}</strong> papers</p><p><strong>${v.datasets.length}</strong> datasets</p><p><strong>${v.benchmarks.length}</strong> benchmark rows</p><p><strong>${v.refs.length}</strong> references</p></aside></section>`});}
function maintenancePage(){ const steps=['Literature Discovery','Candidate Collection','Scope & Relevance Screening','Technical Metadata Extraction','Taxonomy Routing','Localized Survey Update','Validation','Human Review','Versioned Release']; return shell({title:'Maintenance',description:'How agentic assistance and human review maintain the survey.',active:'Maintenance',body:`<header class="page-hero"><div class="section-label">Public maintenance framework</div><h1>Automation proposes.<br>Editors decide.</h1><p>The public release pipeline is designed for traceability, abstention, and human-controlled structural change.</p></header><section class="maintenance-flow" aria-label="Maintenance workflow">${steps.map((s,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><strong>${s}</strong></div>`).join('')}</section><section class="responsibility-grid"><article><div class="section-label">Agent responsibilities</div><h2>Assist and propose</h2><ul>${['Search for new papers','Deduplicate records','Extract technical metadata','Identify datasets and metrics','Propose taxonomy placement','Draft concise summaries','Suggest localized edits','Prepare changelog candidates'].map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="human"><div class="section-label">Human responsibilities</div><h2>Validate and release</h2><ul>${['Final relevance decisions','Factual validation','Taxonomy approval','Structural changes','Benchmark interpretation','Public release approval','Correction of uncertain entries'].map(x=>`<li>${x}</li>`).join('')}</ul></article></section><section class="abstention"><div><div class="section-label">Confidence and abstention</div><h2>Uncertainty pauses publication.</h2><p>Candidate records can be held for review. Only accepted, validated records should enter an official public survey release.</p></div><div class="status-ladder">${['Candidate','Under Review','Needs Verification','Accepted','Rejected'].map(x=>badge(x,x==='Accepted'?'added':x==='Rejected'?'removed':'neutral')).join('')}</div></section><section class="static-note"><h2>Static by design</h2><p>The agentic system runs on author-controlled computers. It updates structured files and survey content in the repository. The public website is generated as a static site and deployed through GitHub Pages.</p></section>`}); }
function aboutPage(){ const bib=`@article{mumcu2026dynamicvad,\n  title={Language Models in Video Anomaly Detection: A Dynamic Survey},\n  author={Mumcu, Furkan and Bekit, Lokman and Jones, Michael J. and Cherian, Anoop and Yilmaz, Yasin},\n  journal={IEEE Access},\n  year={2026},\n  version={${stats.version}},\n  url={https://dynamicvadsurvey.github.io/},\n  note={Website version ${stats.version}, accessed __ACCESS_DATE__}\n}`;
 const authors=[
  ['Furkan Mumcu','University of South Florida','furkan [at] usf.edu','Corresponding author','Received his B.S. degree in Computer Engineering from Bilkent University, Ankara, Turkiye, in 2018, and his M.S. degree in Electrical Engineering from the University of South Florida, Tampa, FL, USA, in 2024, where he is currently pursuing a Ph.D. degree. His research interests include AI security, video anomaly detection, adversarial machine learning, and agentic AI.'],
  ['Lokman Bekit','University of South Florida','lbekit [at] usf.edu','','Received his B.S. degree in Electrical Engineering from the University of South Florida, in 2025. He is currently pursuing a Ph.D. degree in Artificial Intelligence at the University of South Florida. His research interests include video anomaly detection, vision-language models and efficient inference.'],
  ['Michael J. Jones','Mitsubishi Electric Research Laboratories (MERL)','mjones [at] merl.com','','Received his bachelors degree in computer science and mathematics from Rice University in 1990 and then went to the Artificial Intelligence Lab at MIT where he received his Ph.D. in Electrical Engineering and Computer Science in 1997. After MIT, he worked at DEC\'s Cambridge Research Lab before moving to Mitsubishi Electric Research Laboratories (MERL) in Cambridge, Massachusetts, where he is currently a Distinguished Research Scientist in the computer vision group. His research interests include object detection and recognition, machine learning and video anomaly detection.'],
  ['Anoop Cherian','Mitsubishi Electric Research Laboratories (MERL)','cherian [at] merl.com','','Received the undergraduate (honors) degree in computer science and engineering from the National Institute of Technology (NIT), Calicut, India, in 2002, and the MS and PhD degrees from the University of Minnesota, Minneapolis, Minnesota, in 2010 and 2013, respectively. He is a Senior Principal Research Scientist at Mitsubishi Electric Research Labs (MERL) Cambridge, Massachusetts, and an adjunct researcher at the Australian Centre for Robotic Vision (ACRV) at the Australian National University, Canberra, Australia. Before joining ANU, he was a postdoctoral researcher in the LEAR team at INRIA, Grenoble.'],
  ['Yasin Yilmaz','University of South Florida','yasiny [at] usf.edu','','Received the B.S. degree in electrical and electronics engineering from Middle East Technical University, Ankara, Turkiye, in 2008, the M.S. degree in electrical and computer engineering from Koc University, Istanbul, Turkiye, in 2010, and the Ph.D. degree in electrical engineering from Columbia University, New York City, NY, USA, in 2014. He is currently an Associate Professor with the Department of Electrical Engineering, University of South Florida, Tampa, FL, USA. His research interests include machine learning, computer vision, anomaly detection, AI security, IoT security, and their applications in environmental, biomedical, energy, transportation, and communication systems.']
 ];
 return shell({title:'About & Citation',description:'Project summary, citation policy, and contact information.',active:'About',body:`<header class="page-hero"><div class="section-label">About the project</div><h1>A living scholarly system,<br>not a disposable project page.</h1><p>This companion connects a web-native survey, structured literature records, datasets, protocol-aware benchmarks, and a transparent editorial history.</p></header><section class="about-grid"><article><h2>About this website</h2><p>The Dynamic VAD Survey is the maintained web companion to the paper “Language Models in Video Anomaly Detection: A Dynamic Survey.” It makes the survey easier to read, search, update, and cite as the field evolves.</p><p>The Survey area presents the long-form review as web pages. Explore provides structured method records, while Datasets and Benchmarks organize the evidence used across the literature. Updates records the release history and makes changes between frozen versions transparent.</p><p>The website is static and openly accessible. New material may be prepared with agentic-AI assistance, but every public release remains human-reviewed, versioned, and preserved as a frozen archive.</p><h2>Authors & affiliations</h2><ul class="author-list">${authors.map(([name,aff,email,note,bio])=>`<li><strong>${escapeHtml(name)}</strong><span>${escapeHtml(aff)}</span><span>${escapeHtml(email)}</span>${note?`<span>${escapeHtml(note)}</span>`:''}<p>${escapeHtml(bio)}</p></li>`).join('')}</ul><h2>Update policy</h2><p>Routine metadata and localized prose updates may be proposed with agentic assistance. Taxonomy changes, evaluative claims, removals, and public releases require explicit human approval.</p><h2>Contact & repository</h2><p>Repository: <a href="https://github.com/dynamicvadsurvey/dynamicvadsurvey.github.io">github.com/dynamicvadsurvey</a>. For corrections or questions, contact the corresponding author above.</p></article><aside><div class="section-label">Citation guidance</div><h2>How to cite</h2><p>Use one extended paper citation. Keep the archival <code>@article</code> metadata and append the website version, URL, and access date in the same BibTeX entry.</p><blockquote>Dynamic VAD Survey, Version ${stats.version}, accessed <span data-access-date></span>.</blockquote><div class="bibtex"><button id="copy-bibtex" data-copy="${escapeHtml(bib)}">Copy BibTeX</button><pre><code data-dynamic-bibtex>${escapeHtml(bib)}</code></pre></div></aside></section>`}); }

function guideInline(source){const code=[];let html=String(source).replace(/`([^`]+)`/g,(_,value)=>{code.push(`<code>${escapeHtml(value)}</code>`);return `\x01${code.length-1}\x02`});html=escapeHtml(html).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');return html.replace(/\x01(\d+)\x02/g,(_,i)=>code[Number(i)])}
function renderGuideMarkdown(source){const lines=source.replace(/\r/g,'').split('\n');let html='',i=0;while(i<lines.length){const line=lines[i];if(!line.trim()){i++;continue}if(line.startsWith('```')){const language=line.slice(3).trim(),body=[];i++;while(i<lines.length&&!lines[i].startsWith('```'))body.push(lines[i++]);i++;html+=`<pre><code${language?` class="language-${escapeHtml(language)}"`:''}>${escapeHtml(body.join('\n'))}</code></pre>`;continue}const heading=line.match(/^(#{1,6})\s+(.+)$/);if(heading){const level=heading[1].length,id=slugify(heading[2]);html+=`<h${level} id="${id}">${guideInline(heading[2])}</h${level}>`;i++;continue}if(isTableRow(line)&&lines[i+1]&&isTableRule(lines[i+1])){const head=splitRow(line),rows=[];i+=2;while(i<lines.length&&isTableRow(lines[i]))rows.push(splitRow(lines[i++]));html+=`<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${guideInline(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${guideInline(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;continue}const unordered=line.match(/^\s*-\s+(.+)$/),ordered=line.match(/^\s*\d+\.\s+(.+)$/);if(unordered||ordered){const tag=unordered?'ul':'ol',items=[];while(i<lines.length){const match=tag==='ul'?lines[i].match(/^\s*-\s+(.+)$/):lines[i].match(/^\s*\d+\.\s+(.+)$/);if(!match)break;const task=match[1].match(/^\[([ xX])\]\s+(.+)$/);items.push(task?`<li class="task"><input type="checkbox" disabled ${task[1].trim()?'checked':''}>${guideInline(task[2])}</li>`:`<li>${guideInline(match[1])}</li>`);i++}html+=`<${tag}>${items.join('')}</${tag}>`;continue}const quote=line.match(/^>\s?(.*)$/);if(quote){const body=[];while(i<lines.length&&lines[i].startsWith('>'))body.push(lines[i++].replace(/^>\s?/,''));html+=`<blockquote>${guideInline(body.join(' '))}</blockquote>`;continue}const para=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6})\s|^```|^\s*-\s+|^\s*\d+\.\s+|^>/.test(lines[i])&&!(isTableRow(lines[i])&&lines[i+1]&&isTableRule(lines[i+1])))para.push(lines[i++]);html+=`<p>${guideInline(para.join(' '))}</p>`}return html}
function websiteOperationsGuidePage(source){return shell({title:'Website Operations Guide',description:'Internal website operations documentation for the Dynamic VAD Survey.',body:`<header class="page-hero compact"><div class="section-label">Website documentation</div><h1>Website Operations Guide</h1><p>This unlinked page is rendered from the repository’s <code>WEBSITE_OPERATIONS_GUIDE.md</code> source.</p></header><article class="maintenance-guide">${renderGuideMarkdown(source)}</article>`})}

await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
const pages = new Map();
pages.set('/',home()); pages.set('/explore/',explorer()); pages.set('/datasets/',datasetsPage()); pages.set('/benchmarks/',benchmarksPage()); pages.set('/updates/',updatesPage()); pages.set('/updates/compare/',comparePage()); pages.set('/maintenance/',maintenancePage()); pages.set('/about/',aboutPage());
pages.set('/website-operations-guide/',websiteOperationsGuidePage(await readFile(path.join(root,'WEBSITE_OPERATIONS_GUIDE.md'),'utf8')));
for(const [version,frozen] of Object.entries(frozenReleases))pages.set(`/versions/${version}/`,versionLandingPage(frozen));
const sectionHtml=[];
for (let i=0;i<sections.length;i++){
  const md=await readFile(path.join(root,sections[i][2]),'utf8');
  const html=markdown(md);
  sectionHtml.push(html);
  pages.set(`/survey/${sections[i][0]}/`,surveyPage(i,html));
}
const bibliography=`<section class="references"><h1 id="references">References</h1>${refs.map(r=>`<p id="ref-${r.id}"><span>[${r.id}]</span><strong>${r.title}</strong><br>${r.authors}. ${r.venue}. <a href="${r.url}">Source*</a></p>`).join('')}</section>`;
const fullSurveyPage=surveyPage(0,sectionHtml.join('<hr class="section-break">')+bibliography,true);
pages.set('/survey/full/',fullSurveyPage);
pages.set('/survey/',fullSurveyPage);
for(const [version,frozen] of Object.entries(frozenReleases)){
  const routeBase=`/versions/${version}/survey`,archivedSections=[];
  const archiveSectionDefs=[];
  for(const definition of sections){const relative=definition[2].replace(/^content\//,'');try{await readFile(path.join(root,frozen.root,'content',relative));archiveSectionDefs.push(definition)}catch(error){if(error.code!=='ENOENT')throw error}}
  const options={citationBase:`${routeBase}/full/`,figureBase:`/versions/${version}/assets/figures`};
  for(let i=0;i<archiveSectionDefs.length;i++){
    const relative=archiveSectionDefs[i][2].replace(/^content\//,'');
    const html=markdown(await readFile(path.join(root,frozen.root,'content',relative),'utf8'),options);
    archivedSections.push(html);
    pages.set(`${routeBase}/${archiveSectionDefs[i][0]}/`,surveyPage(i,html,false,{version,stats:frozen.stats,routeBase,sections:archiveSectionDefs}));
  }
  const archivedBibliography=`<section class="references"><h1 id="references">References</h1>${frozen.refs.map(r=>`<p id="ref-${r.id}"><span>[${r.id}]</span><strong>${r.title}</strong><br>${r.authors}. ${r.venue}. <a href="${r.url}">Source*</a></p>`).join('')}</section>`;
  const archivedFull=surveyPage(0,archivedSections.join('<hr class="section-break">')+archivedBibliography,true,{version,stats:frozen.stats,routeBase,sections:archiveSectionDefs});
  pages.set(`${routeBase}/full/`,archivedFull);pages.set(`${routeBase}/`,archivedFull);
}
for(const p of papers) pages.set(`/papers/${p.slug}/`,paperPage(p));
for (const [route,html] of pages){
  const dir=path.join(out,route); await mkdir(dir,{recursive:true});
  const depth=route.split('/').filter(Boolean).length;
  const rel=depth?'../'.repeat(depth):'';
  const portableHtml=html.replaceAll('href="/assets/','href="'+rel+'assets/').replaceAll('src="/assets/','src="'+rel+'assets/').replaceAll('href="/favicon.svg','href="'+rel+'favicon.svg');
  await writeFile(path.join(dir,'index.html'),portableHtml);
}
await mkdir(path.join(out,'assets'),{recursive:true}); await cp(path.join(root,'src/site.css'),path.join(out,'assets/site.css')); await cp(path.join(root,'src/site.js'),path.join(out,'assets/site.js')); await cp(path.join(root,'public/favicon.svg'),path.join(out,'favicon.svg'));
await cp(path.join(root,'src/figures'),path.join(out,'assets/figures'),{recursive:true});
for(const [version,frozen] of Object.entries(frozenReleases)){
  const releaseOut=path.join(out,'versions',version);await mkdir(path.join(releaseOut,'assets'),{recursive:true});
  await cp(path.join(root,frozen.root,'figures'),path.join(releaseOut,'assets/figures'),{recursive:true});
  await cp(path.join(root,frozen.root,'data'),path.join(releaseOut,'data'),{recursive:true});
  await cp(path.join(root,frozen.root,'release.json'),path.join(releaseOut,'release.json'));
}
await cp(path.join(root,'node_modules/katex/dist/katex.min.css'),path.join(out,'assets/katex.min.css'));
await cp(path.join(root,'node_modules/katex/dist/fonts'),path.join(out,'assets/fonts'),{recursive:true});
await mkdir(path.join(out,'data'),{recursive:true}); await cp(path.join(root,'data'),path.join(out,'data'),{recursive:true});
const urls=[...pages.keys()].map(p=>`  <url><loc>https://dynamicvadsurvey.github.io${p}</loc></url>`).join('\n');
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>`);
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://dynamicvadsurvey.github.io/sitemap.xml\n');
await writeFile(path.join(out,'.nojekyll'),'');
await cp(path.join(root,'WEBSITE_OPERATIONS_GUIDE.md'),path.join(out,'WEBSITE_OPERATIONS_GUIDE.md'));
console.log(`Built ${pages.size} pages in dist/`);
