import { readFile, writeFile, mkdir, rm, cp, readdir } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const out = path.join(root, 'dist');
const readJson = async (p) => JSON.parse(await readFile(path.join(root, p), 'utf8'));
const [stats, papers, datasets, benchmarks, versions, refs] = await Promise.all([
  readJson('data/statistics.json'), readJson('data/papers.json'), readJson('data/datasets.json'),
  readJson('data/benchmarks.json'), readJson('data/versions.json'), readJson('data/references.json')
]);
const snapshots=Object.fromEntries(await Promise.all(versions.map(async v=>[v.version,await readJson(`versions/${v.version}/snapshot.json`)])));
const diffFiles=(await readdir(path.join(root,'data/diffs'))).filter(x=>x.endsWith('.json')).sort();
const diffs=Object.fromEntries(await Promise.all(diffFiles.map(async f=>{const d=await readJson(`data/diffs/${f}`);return [`${d.from}--${d.to}`,d]})));

const sections = [
  ['introduction','Introduction','content/introduction.md'],
  ['problem-settings','Problem Settings and Supervision','content/problem-settings.md'],
  ['datasets','Datasets','content/datasets.md'],
  ['evaluation','Evaluation Metrics','content/evaluation.md'],
  ['methods/semi-supervised','Unsupervised and Semi-Supervised','content/methods/semi-supervised.md'],
  ['methods/weakly-supervised','Weakly Supervised','content/methods/weakly-supervised.md'],
  ['methods/training-free','Training-Free','content/methods/training-free.md'],
  ['methods/instruction-tuned','Instruction-Tuned','content/methods/instruction-tuned.md'],
  ['methods/open-world','Open-World and Open-Vocabulary','content/methods/open-world.md'],
  ['maintenance','Dynamic Survey Maintenance','content/maintenance.md'],
  ['challenges','Challenges and Future Directions','content/challenges.md'],
  ['conclusion','Conclusion','content/conclusion.md']
];

const escapeHtml = (s='') => String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const slugify = s => s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function markdown(md) {
  const lines = md.trim().split(/\n/); let html = '', para = [];
  const flush = () => { if (para.length) { html += `<p>${inline(para.join(' '))}</p>`; para=[]; } };
  for (const line of lines) {
    if (!line.trim()) { flush(); continue; }
    if (line.startsWith('$$')) { flush(); html += `<div class="equation" role="math">${inline(line.replace(/^\$\$|\$\$$/g,''))}</div>`; continue; }
    const h = line.match(/^(#{1,3})\s+(.+)/);
    if (h) { flush(); const level=h[1].length, id=slugify(h[2]); html += `<h${level} id="${id}">${inline(h[2])}<a class="anchor" href="#${id}" aria-label="Link to this heading">#</a></h${level}>`; continue; }
    para.push(line);
  }
  flush(); return html;
}
function inline(s) {
  return escapeHtml(s)
    .replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
    .replace(/\[(\d+)\]/g,(_,n)=>`<a class="citation" href="/survey/full/#ref-${n}" title="View reference">[${n}]</a>`)
    .replace(/\$(.+?)\$/g,'<span class="math">$1</span>');
}
const nav = [
 ['Home','/'],['Survey','/survey/introduction/'],['Explore','/explore/'],['Datasets','/datasets/'],
 ['Benchmarks','/benchmarks/'],['Updates','/updates/'],['Maintenance','/maintenance/'],['About','/about/']
];
const rootPrefixScript = `<script>const projectHost=location.hostname.endsWith('github.io')&&location.hostname!=='dynamicvadsurvey.github.io';const segment=projectHost?location.pathname.split('/')[1]:'';document.documentElement.dataset.base=segment?'/'+segment+'/':'/'</script>`;
const href = p => p;
function shell({title, description, active='', body, extra=''}) {
  const links=nav.map(([label,url])=>`<a href="${href(url)}" ${active===label?'aria-current="page"':''}>${label}</a>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} — Dynamic VAD Survey</title><meta name="description" content="${escapeHtml(description)}"><meta name="theme-color" content="#17324d"><meta property="og:title" content="${escapeHtml(title)} — Dynamic VAD Survey"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/assets/site.css">${rootPrefixScript}</head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="/"><span class="brand-mark">DV</span><span>Dynamic VAD Survey<small>Living scholarly resource</small></span></a><button class="menu-button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav id="site-nav" aria-label="Primary">${links}<a class="pdf-button" href="/survey/full/" title="Sample web snapshot; archival PDF not yet supplied">Read Survey PDF*</a></nav></div></header><main id="main">${body}</main><footer><div><strong>Dynamic VAD Survey</strong><p>A continuously maintained, human-reviewed survey companion.</p></div><div><a href="/maintenance/">Update policy</a><a href="/about/">Citation</a><a href="/updates/">Version ${stats.version}</a></div><p class="fine-print">* Archival PDF not supplied; the PDF action opens the printable full-document sample.</p></footer><script src="/assets/site.js" defer></script>${extra}</body></html>`;
}
function badge(s, cls='') { return `<span class="badge ${cls}">${escapeHtml(s)}</span>`; }
const sampleBanner = `<aside class="sample-banner"><strong>Representative sample edition</strong><span>Interactions and architecture are complete; records and prose explicitly marked sample await the reviewed corpus.</span></aside>`;
function home() {
 const statItems=[['Papers',stats.papers],['Datasets',stats.datasets],['Paradigms',stats.paradigms],['Current Version',stats.version],['Last Updated',stats.lastUpdated]].map(([k,v])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('');
 const citation=`@inproceedings{dynamicvadsurvey2026,\n  title={Language Models in Video Anomaly Detection: A Sustainable Dynamic Survey},\n  author={Authors to be supplied},\n  booktitle={Proceedings venue to be supplied},\n  year={2026},\n  version={${stats.version}},\n  url={https://dynamicvadsurvey.github.io/},\n  note={Website version ${stats.version}, accessed ${stats.lastUpdatedFull}}\n}`;
 return shell({title:'Language Models in Video Anomaly Detection',description:'A continuously maintained survey of language-model-based video anomaly detection.',active:'Home',body:`${sampleBanner}<section class="hero"><div class="eyebrow">A sustainable dynamic survey · ${stats.version}</div><h1>Language Models in<br><em>Video Anomaly Detection</em></h1><p>A continuously maintained, agentic-AI-assisted survey covering methods, datasets, benchmarks, evaluation protocols, and emerging research directions, with human-reviewed releases.</p><div class="actions"><a class="button primary" href="/survey/introduction/">Explore the Survey</a><a class="button" href="/explore/">Browse Methods</a><a class="text-action" href="/updates/">View latest updates →</a></div></section><section class="status-strip" aria-label="Project status">${statItems}</section><section class="citation-home"><div><div class="section-label">How to cite this resource</div><h2>Cite the paper.<br>Reference the version.</h2><p>Use the archival paper’s standard BibTeX citation. The maintained website version, URL, and access date are included as additional fields in that same entry.</p><a href="/about/">Full citation guidance →</a></div><div class="citation-example"><div class="citation-example-head"><span>Extended paper BibTeX</span><button class="copy-citation" data-copy="${escapeHtml(citation)}">Copy BibTeX</button></div><pre><code>${escapeHtml(citation)}</code></pre><p>Replace the clearly marked author, venue, and archival metadata once the final paper citation is supplied.</p></div></section><section class="changes"><div><div class="section-label">Latest update · Version 1.2</div><h2>What changed recently</h2></div><div class="change-counts"><span><b>+ 8</b> new methods</span><span><b>+ 2</b> new datasets</span><span><b>~ 3</b> benchmark corrections</span><span><b>~</b> Training-free section revised</span></div><a class="button inverse" href="/updates/">View full changelog</a></section><section class="workflow-home"><div><div class="section-label">Transparent maintenance</div><h2>Assisted by agents.<br>Released by humans.</h2><p>Agentic tools assist with discovery, summarization, routing, and localized updates. Public releases remain human-reviewed and versioned.</p></div><ol>${['Paper discovery','Relevance screening','Technical extraction','Taxonomy routing','Human review','Versioned release'].map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${x}</li>`).join('')}</ol></section>`});
}
const toc = sections.map(([slug,title],i)=>`<a href="/survey/${slug}/"><span>${i+1}</span>${title}</a>`).join('');
function surveyPage(index, html, full=false) {
 const [,title]=sections[index]||['','Full Survey'];
 const headings=[...html.matchAll(/<h([23]) id="([^"]+)">([^<]+)/g)].map(m=>`<a href="#${m[2]}" class="depth-${m[1]}">${m[3]}</a>`).join('');
 const previous=index>0?sections[index-1]:null, next=index<sections.length-1?sections[index+1]:null;
 const versionOptions=versions.map(v=>`<option value="${v.version}" ${v.version===stats.version?'selected':''}>${v.version} — ${v.status}</option>`).join('');
 return shell({title:full?'Full Survey':title,description:`Web-native survey section: ${title}.`,active:'Survey',body:`${sampleBanner}<div class="survey-layout"><aside class="survey-toc"><div class="aside-title">Survey contents</div><nav>${toc}<a class="full-link" href="/survey/full/">Full document mode</a></nav><div class="version-select"><label for="survey-version">Reading version</label><select id="survey-version" data-current-version="${stats.version}">${versionOptions}</select><small>Older releases open their immutable snapshots.</small></div></aside><article class="survey-article"><div class="version-bar"><span><b>Survey Version</b>${stats.version}</span><span><b>Last Updated</b>${stats.lastUpdatedFull}</span><span><b>Last Changed In</b>v1.2</span><a href="/updates/compare/?section=${encodeURIComponent(title)}">View changes since v1.1 →</a></div>${html}${!full?`<nav class="page-turn">${previous?`<a href="/survey/${previous[0]}/">← <small>Previous</small>${previous[1]}</a>`:'<span></span>'}${next?`<a class="next" href="/survey/${next[0]}/"><small>Next</small>${next[1]} →</a>`:'<span></span>'}</nav>`:''}</article><aside class="on-page"><details open><summary>On this page</summary><nav>${headings||'<span>Full document</span>'}</nav></details><a class="related-card" href="/explore/"><small>Related resource</small>Browse structured method records →</a></aside></div>`});
}
function paperRows() { return papers.map(p=>`<tr data-record data-search="${escapeHtml([p.method,p.title,p.authors.join(' '),p.venue,p.datasets.join(' '),p.modelTypes.join(' '),p.tasks.join(' ')].join(' ').toLowerCase())}" data-paradigm="${escapeHtml(p.paradigm)}" data-model="${escapeHtml(p.modelTypes.join('|'))}" data-training="${escapeHtml(p.training)}"><td><a href="/papers/${p.slug}/"><strong>${escapeHtml(p.method)}</strong><small>${escapeHtml(p.title)}</small></a></td><td>${p.year}</td><td>${badge(p.paradigm)}</td><td>${p.modelTypes.map(x=>badge(x,'neutral')).join('')}</td><td>${p.tasks.slice(0,3).join(', ')}</td><td>${p.code?'Yes':'—'}</td></tr>`).join(''); }
function paperCards() { return papers.map(p=>`<article class="paper-card" data-record data-search="${escapeHtml(JSON.stringify(p).toLowerCase())}" data-paradigm="${escapeHtml(p.paradigm)}" data-model="${escapeHtml(p.modelTypes.join('|'))}" data-training="${escapeHtml(p.training)}"><div>${badge(p.paradigm)} ${badge(String(p.year),'neutral')}</div><h3><a href="/papers/${p.slug}/">${escapeHtml(p.method)}</a></h3><h4>${escapeHtml(p.title)}</h4><p>${escapeHtml(p.summary)}</p><div class="card-meta"><span>${escapeHtml(p.venue)} ${p.year}</span><span>${p.code?'Code listed':'No code listed'}</span></div></article>`).join(''); }
function explorer() {
 const opts=(arr)=>[...new Set(arr)].sort().map(x=>`<option>${escapeHtml(x)}</option>`).join('');
 return shell({title:'Explore the Literature',description:'Search and filter language-model-based VAD papers and methods.',active:'Explore',body:`${sampleBanner}<header class="page-hero"><div class="section-label">Structured literature explorer</div><h1>Find methods by the question you are asking.</h1><p>Search representative records by title, method, dataset, model, task, author, or venue.</p></header><section class="explorer-shell"><aside class="filters"><div class="filter-heading"><h2>Filters</h2><button id="clear-filters" class="link-button">Clear all</button></div><label>Paradigm<select id="filter-paradigm"><option value="">All paradigms</option>${opts(papers.map(p=>p.paradigm))}</select></label><label>Model type<select id="filter-model"><option value="">All model types</option>${opts(papers.flatMap(p=>p.modelTypes))}</select></label><label>Training<select id="filter-training"><option value="">All training</option>${opts(papers.map(p=>p.training))}</select></label><div class="filter-note"><strong>Sample corpus</strong><p>${papers.length} representative records demonstrate the interface; the status count reflects the target reviewed corpus.</p></div></aside><div class="results"><div class="search-row"><label class="search"><span class="sr-only">Search papers</span><input id="paper-search" type="search" placeholder="Search papers, methods, datasets, models, or tasks…"></label><div class="view-toggle" role="group" aria-label="Display style"><button class="active" data-view="table" aria-pressed="true">Table</button><button data-view="cards" aria-pressed="false">Cards</button></div></div><div class="result-summary"><span><strong id="result-count">${papers.length}</strong> sample methods</span><span>Sorted by year, newest first</span></div><div id="table-view" class="table-wrap"><table><thead><tr><th>Method</th><th>Year</th><th>Paradigm</th><th>Model</th><th>Tasks</th><th>Code</th></tr></thead><tbody>${paperRows()}</tbody></table></div><div id="card-view" class="paper-grid" hidden>${paperCards()}</div><div id="no-results" class="empty-state" hidden><h3>No matching methods</h3><p>Try clearing one or more filters.</p></div></div></section>`});
}
function paperPage(p) { const links=[['Paper',p.paperUrl],p.codeUrl?['Code',p.codeUrl]:null,['Survey section',`/survey/${p.paradigm==='Training-Free'?'methods/training-free':'introduction'}/`]].filter(Boolean); return shell({title:p.method,description:p.title,active:'Explore',body:`${sampleBanner}<article class="detail-page"><a class="back" href="/explore/">← Back to literature explorer</a><header class="paper-header"><div>${badge(p.paradigm)} ${badge(p.status,'warning')}</div><h1>${escapeHtml(p.method)}</h1><p>${escapeHtml(p.title)}</p><span>${escapeHtml(p.venue)} · ${p.year}</span></header><div class="detail-grid"><div><section><div class="section-label">Human-reviewed summary status</div><h2>Survey summary</h2><p>${escapeHtml(p.summary)}</p></section><section><div class="section-label">Taxonomy placement</div><h2>${escapeHtml(p.taxonomy.split(' / ')[0])}</h2><div class="taxonomy-path">${p.taxonomy.split(' / ').map((x,i)=>`<span style="--i:${i}">${escapeHtml(x)}</span>`).join('')}</div></section><section><div class="section-label">Method characteristics</div><div class="badge-cloud">${[p.paradigm,...p.badges].map(x=>badge(x)).join('')}</div></section></div><aside class="metadata-card"><h2>Metadata</h2>${[['Model types',p.modelTypes.join(', ')],['Training',p.training],['Tasks',p.tasks.join(', ')],['Datasets',p.datasets.join(', ')],['Authors',p.authors.join(', ')]].map(([k,v])=>`<div><dt>${k}</dt><dd>${escapeHtml(v)}</dd></div>`).join('')}<div class="resource-links">${links.map(([k,u])=>`<a href="${u}">${k} →</a>`).join('')}</div><h3>Version history</h3><dl><div><dt>Added in</dt><dd>${p.added}</dd></div><div><dt>Last updated</dt><dd>${p.updated}</dd></div><div><dt>Last verified</dt><dd>${p.verified}</dd></div></dl></aside></div></article>`}); }
function datasetsPage(){ const groups=[...new Set(datasets.map(d=>d.group))]; return shell({title:'Datasets',description:'Interactive dataset metadata for video anomaly detection.',active:'Datasets',body:`${sampleBanner}<header class="page-hero"><div class="section-label">Evidence catalog</div><h1>Datasets shape what anomaly systems can claim.</h1><p>Filter representative records by annotation and task. Every row carries a verification note.</p></header><section class="data-page"><div class="dataset-groups">${groups.map(g=>`<button data-dataset-group="${g}"><span>${datasets.filter(d=>d.group===g).length}</span>${g}</button>`).join('')}</div><div class="table-tools"><input id="dataset-search" type="search" placeholder="Search datasets or annotations…"><button id="dataset-clear" class="button small">Show all</button></div><div class="table-wrap"><table class="dataset-table"><thead><tr><th>Dataset</th><th>Year / domain</th><th>Scale</th><th>Temporal</th><th>Spatial</th><th>Semantic</th><th>Tasks</th></tr></thead><tbody>${datasets.map(d=>`<tr data-dataset data-group="${d.group}" data-search="${escapeHtml(JSON.stringify(d).toLowerCase())}"><td><strong>${d.name}</strong><small>${badge(d.group,'neutral')}<br>${d.verified}</small></td><td>${d.year}<small>${d.domain}</small></td><td>${d.scale}</td><td>${d.temporal}</td><td>${d.spatial}</td><td>${d.semantic}</td><td>${d.tasks.join(', ')}</td></tr>`).join('')}</tbody></table></div></section>`}); }
function benchmarksPage(){ return shell({title:'Benchmarks',description:'Protocol-aware benchmark comparison tables.',active:'Benchmarks',body:`${sampleBanner}<header class="page-hero"><div class="section-label">Protocol before rank</div><h1>Comparison tables with their caveats attached.</h1><p>Representative values show source, protocol, verification, and comparability rather than implying a universal leaderboard.</p></header><section class="data-page"><div class="notice"><strong>Do not compare blindly.</strong><span>Rows may use different protocols. Reliability labels describe evidence, not method quality.</span></div>${[...new Set(benchmarks.map(b=>b.group))].map(g=>`<section class="benchmark-group"><h2>${g}</h2><div class="table-wrap"><table><thead><tr><th>Method</th><th>Dataset</th><th>Metric</th><th>Value</th><th>Protocol</th><th>Reliability</th></tr></thead><tbody>${benchmarks.filter(b=>b.group===g).map((b,i)=>`<tr><td>${b.method}</td><td>${b.dataset}</td><td>${b.metric}</td><td><button class="value-button" data-dialog="benchmark-${slugify(g)}-${i}">${b.value}</button><dialog id="benchmark-${slugify(g)}-${i}"><button class="dialog-close" aria-label="Close">×</button><h3>${b.method}</h3><p><strong>${b.dataset} ${b.metric}: ${b.value}</strong></p><dl><div><dt>Source</dt><dd>${b.source}</dd></div><div><dt>Added in</dt><dd>v1.0</dd></div>${b.previous?`<div><dt>Previous value</dt><dd>${b.previous}</dd></div><div><dt>Corrected in</dt><dd>${b.corrected}</dd></div>`:''}</dl></dialog></td><td>${b.protocol}<small>${b.comparable?'Comparable within stated sample':'Not directly comparable'}</small></td><td>${badge(b.reliability,b.reliability.includes('Unclear')?'warning':'')}</td></tr>`).join('')}</tbody></table></div></section>`).join('')}</section>`}); }
function updatesPage(){ return shell({title:'Updates',description:'Changelog and version history for the maintained survey.',active:'Updates',body:`${sampleBanner}<header class="page-hero"><div class="section-label">Editorial record</div><h1>Every public change gets a reason and a version.</h1><p>Review release summaries, open immutable static snapshots, and compare precomputed versions.</p><div class="actions"><a class="button primary" href="/updates/compare/">Compare versions</a><a class="button" href="#history">Version history</a></div></header><section class="updates-layout"><article><div class="release-kicker"><span>Latest release</span><time>${versions[0].date}</time></div><h2>${versions[0].version} — ${versions[0].title}</h2><div class="changelog-grid"><div><h3>+ Added</h3><ul><li>New method records</li><li>FineVAU and VAGU sample datasets</li><li>QVAD sample framework</li></ul></div><div><h3>~ Updated</h3><ul><li>Training-free discussion</li><li>Open-world taxonomy</li><li>Benchmark comparison data</li></ul></div><div><h3>! Corrected</h3><ul><li>Venue metadata</li><li>UCF-Crime benchmark value</li></ul></div><div><h3>↔ Storage</h3><p>Immutable mock snapshot generated and hosted.</p></div></div></article><aside><h2>Release metadata</h2><dl><div><dt>Git tag</dt><dd>${versions[0].tag}</dd></div><div><dt>Status</dt><dd>${badge(versions[0].status)}</dd></div><div><dt>Snapshot</dt><dd><a href="/versions/${versions[0].version}/">Open ${versions[0].version}</a></dd></div></dl><a class="button full" href="/updates/compare/">Compare versions</a></aside></section><section id="history" class="history"><div class="section-label">Official releases</div><h2>Version history</h2>${versions.map(v=>`<article><div><span class="version-dot"></span><time>${v.date}</time></div><div><h3>${v.version} · ${v.title}</h3><p>${v.summary}</p><span>${v.tag}</span> · <a href="/versions/${v.version}/">Open snapshot →</a></div><div>${badge(v.status,v.status==='Archival'?'neutral':'')}</div></article>`).join('')}</section>`}); }
function comparePage(){ const initial=diffs['v1.0--v1.2']||Object.values(diffs)[0]; const versionOptions=versions.slice().reverse().map(v=>`<option value="${v.version}">${v.version}</option>`).join(''); return shell({title:'Compare Versions',description:'Unified semantic diff between survey releases.',active:'Updates',body:`<header class="page-hero compact"><div class="section-label">Version transparency</div><h1>Compare survey versions</h1><p>All comparisons below are generated at build time from stored static snapshots.</p></header><section class="compare-controls"><label>From<select id="diff-from">${versionOptions}</select></label><span>→</span><label>To<select id="diff-to">${versionOptions}</select></label><button id="compare-submit" class="button primary">Compare versions</button></section><div id="compare-error" class="empty-state" hidden></div><section id="diff-summary" class="diff-summary"></section><section id="diff-panel" class="diff-panel" data-view="unified"><div class="diff-toolbar"><div role="group" aria-label="Comparison display"><button class="active" data-diff-view="unified" aria-pressed="true">Unified</button><button data-diff-view="side" aria-pressed="false">Side-by-side</button><button data-diff-view="summary" aria-pressed="false">Summary only</button></div><label>Section<select id="diff-section"><option value="">All sections</option></select></label></div><div class="side-headings" aria-hidden="true"><span>Earlier version</span><span>Later version</span></div><div id="diff-list"></div></section><script id="version-diffs" type="application/json">${JSON.stringify(diffs).replace(/</g,'\\u003c')}</script><script>document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#diff-from').value='${initial.from}';document.querySelector('#diff-to').value='${initial.to}';document.querySelector('#compare-submit').click()})</script>`}); }
function snapshotPage(s){return shell({title:`Survey Snapshot ${s.version}`,description:`Immutable static sample snapshot for ${s.version}.`,active:'Updates',body:`${sampleBanner}<header class="page-hero compact"><div class="section-label">Immutable version snapshot</div><h1>${s.version}</h1><p>Released ${s.date} · Git tag ${s.tag} · ${s.status}</p><div class="actions"><a class="button primary" href="/updates/compare/?from=${s.version}">Compare this version</a><a class="button" href="/updates/">Version history</a></div></header><section class="snapshot-grid"><article><h2>Survey prose snapshot</h2>${Object.entries(s.sections).map(([k,v])=>`<section><h3>${escapeHtml(k)}</h3><p>${escapeHtml(v)}</p></section>`).join('')}</article><aside><h2>Structured records</h2><p><strong>${s.papers.length}</strong> sample papers</p><ul>${s.papers.map(p=>`<li>${escapeHtml(p.method)} <small>${escapeHtml(p.paradigm)}</small></li>`).join('')}</ul><p><strong>${s.datasets.length}</strong> sample datasets</p><ul>${s.datasets.map(d=>`<li>${escapeHtml(d.name)}</li>`).join('')}</ul><h3>Benchmark snapshot</h3>${s.benchmarks.map(b=>`<p>${escapeHtml(b.method)} · ${escapeHtml(b.dataset)} ${escapeHtml(b.metric)}: <strong>${escapeHtml(b.value)}</strong></p>`).join('')}</aside></section>`});}
function maintenancePage(){ const steps=['Literature Discovery','Candidate Collection','Scope & Relevance Screening','Technical Metadata Extraction','Taxonomy Routing','Localized Survey Update','Validation','Human Review','Versioned Release']; return shell({title:'Maintenance',description:'How agentic assistance and human review maintain the survey.',active:'Maintenance',body:`${sampleBanner}<header class="page-hero"><div class="section-label">Public maintenance framework</div><h1>Automation proposes.<br>Editors decide.</h1><p>The public release pipeline is designed for traceability, abstention, and human-controlled structural change.</p></header><section class="maintenance-flow" aria-label="Maintenance workflow">${steps.map((s,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><strong>${s}</strong></div>`).join('')}</section><section class="responsibility-grid"><article><div class="section-label">Agent responsibilities</div><h2>Assist and propose</h2><ul>${['Search for new papers','Deduplicate records','Extract technical metadata','Identify datasets and metrics','Propose taxonomy placement','Draft concise summaries','Suggest localized edits','Prepare changelog candidates'].map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="human"><div class="section-label">Human responsibilities</div><h2>Validate and release</h2><ul>${['Final relevance decisions','Factual validation','Taxonomy approval','Structural changes','Benchmark interpretation','Public release approval','Correction of uncertain entries'].map(x=>`<li>${x}</li>`).join('')}</ul></article></section><section class="abstention"><div><div class="section-label">Confidence and abstention</div><h2>Uncertainty pauses publication.</h2><p>Candidate records can be held for review. Only accepted, validated records should enter an official public survey release.</p></div><div class="status-ladder">${['Candidate','Under Review','Needs Verification','Accepted','Rejected'].map(x=>badge(x,x==='Accepted'?'added':x==='Rejected'?'removed':'neutral')).join('')}</div></section><section class="static-note"><h2>Static by design</h2><p>The agentic system runs on author-controlled computers. It updates structured files and survey content in the repository. The public website is generated as a static site and deployed through GitHub Pages.</p></section>`}); }
function aboutPage(){ const bib=`@inproceedings{dynamicvadsurvey2026,\n  title={Language Models in Video Anomaly Detection: A Sustainable Dynamic Survey},\n  author={Authors to be supplied},\n  booktitle={Proceedings venue to be supplied},\n  year={2026},\n  version={${stats.version}},\n  url={https://dynamicvadsurvey.github.io/},\n  note={Website version ${stats.version}, accessed ${stats.lastUpdatedFull}}\n}`; return shell({title:'About & Citation',description:'Project summary, citation policy, and contact information.',active:'About',body:`${sampleBanner}<header class="page-hero"><div class="section-label">About the project</div><h1>A living scholarly system,<br>not a disposable project page.</h1><p>This companion connects a web-native survey, structured literature records, datasets, protocol-aware benchmarks, and a transparent editorial history.</p></header><section class="about-grid"><article><h2>Survey abstract</h2><p>This sample abstract describes a survey of language-model-based video anomaly detection across supervision settings, model roles, datasets, evaluation, and emerging challenges. Replace it with the reviewed archival abstract before release.</p><h2>Authors & affiliations</h2><p><strong>To be supplied by the survey authors.</strong> This information is intentionally not invented.</p><h2>Update policy</h2><p>Routine metadata and localized prose updates may be proposed with agentic assistance. Taxonomy changes, evaluative claims, removals, and public releases require explicit human approval.</p><h2>Contact & repository</h2><p>Repository and contact URLs have not been supplied. Add verified links in <code>data/project.json</code> in the next editorial pass.</p></article><aside><div class="section-label">Citation guidance</div><h2>How to cite</h2><p>Use one extended paper citation. Keep the archival <code>@inproceedings</code> metadata and append the website version, URL, and access date in the same BibTeX entry.</p><blockquote>Dynamic VAD Survey, Version ${stats.version}, accessed ${stats.lastUpdatedFull}.</blockquote><div class="bibtex"><button id="copy-bibtex" data-copy="${escapeHtml(bib)}">Copy BibTeX</button><pre><code>${escapeHtml(bib)}</code></pre></div><p class="fine-print">Sample citation: archival authors and proceedings metadata must be verified before publication.</p></aside></section>`}); }

await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
const pages = new Map();
pages.set('/',home()); pages.set('/explore/',explorer()); pages.set('/datasets/',datasetsPage()); pages.set('/benchmarks/',benchmarksPage()); pages.set('/updates/',updatesPage()); pages.set('/updates/compare/',comparePage()); pages.set('/maintenance/',maintenancePage()); pages.set('/about/',aboutPage());
for(const [version,snapshot] of Object.entries(snapshots)) pages.set(`/versions/${version}/`,snapshotPage(snapshot));
const sectionHtml=[];
for (let i=0;i<sections.length;i++){ const md=await readFile(path.join(root,sections[i][2]),'utf8'); const html=markdown(md); sectionHtml.push(html); pages.set(`/survey/${sections[i][0]}/`,surveyPage(i,html)); }
const bibliography=`<section class="references"><h1 id="references">References</h1>${refs.map(r=>`<p id="ref-${r.id}"><span>[${r.id}]</span><strong>${r.title}</strong><br>${r.authors}. ${r.venue}. <a href="${r.url}">Source*</a></p>`).join('')}</section>`;
pages.set('/survey/full/',surveyPage(0,sectionHtml.join('<hr class="section-break">')+bibliography,true));
for(const p of papers) pages.set(`/papers/${p.slug}/`,paperPage(p));
for (const [route,html] of pages){
  const dir=path.join(out,route); await mkdir(dir,{recursive:true});
  const depth=route.split('/').filter(Boolean).length;
  const rel=depth?'../'.repeat(depth):'';
  const portableHtml=html.replaceAll('href="/assets/','href="'+rel+'assets/').replaceAll('src="/assets/','src="'+rel+'assets/').replaceAll('href="/favicon.svg','href="'+rel+'favicon.svg');
  await writeFile(path.join(dir,'index.html'),portableHtml);
}
await mkdir(path.join(out,'assets'),{recursive:true}); await cp(path.join(root,'src/site.css'),path.join(out,'assets/site.css')); await cp(path.join(root,'src/site.js'),path.join(out,'assets/site.js')); await cp(path.join(root,'public/favicon.svg'),path.join(out,'favicon.svg'));
await mkdir(path.join(out,'data'),{recursive:true}); await cp(path.join(root,'data'),path.join(out,'data'),{recursive:true});
const urls=[...pages.keys()].map(p=>`  <url><loc>https://dynamicvadsurvey.github.io${p}</loc></url>`).join('\n');
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>`);
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://dynamicvadsurvey.github.io/sitemap.xml\n');
await writeFile(path.join(out,'.nojekyll'),'');
console.log(`Built ${pages.size} pages in dist/`);
