const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const base=document.documentElement.dataset.base||'/';
if(base!=='/') $$('a[href^="/"]').forEach(a=>{ if(!a.href.includes('#sample-link')) a.href=base.replace(/\/$/,'')+a.getAttribute('href'); });

const menu=$('.menu-button'), nav=$('#site-nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});

function initExplorer(){
 const search=$('#paper-search'); if(!search)return;
 const filters={paradigm:$('#filter-paradigm'),model:$('#filter-model'),training:$('#filter-training')};
 const params=new URLSearchParams(location.search); if(params.get('paradigm'))filters.paradigm.value=params.get('paradigm');
 const update=()=>{const q=search.value.toLowerCase().trim();let visible=0;$$('[data-record]').forEach(el=>{const ok=(!q||el.dataset.search.includes(q))&&(!filters.paradigm.value||el.dataset.paradigm===filters.paradigm.value)&&(!filters.model.value||el.dataset.model.split('|').includes(filters.model.value))&&(!filters.training.value||el.dataset.training===filters.training.value);el.hidden=!ok;if(ok)visible++});$('#result-count').textContent=visible/2;$('#no-results').hidden=visible>0;};
 search.addEventListener('input',update);Object.values(filters).forEach(x=>x.addEventListener('change',update));
 $('#clear-filters').addEventListener('click',()=>{search.value='';Object.values(filters).forEach(x=>x.value='');history.replaceState({},'',location.pathname);update()});
 $$('.view-toggle button').forEach(b=>b.addEventListener('click',()=>{$$('.view-toggle button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});const cards=b.dataset.view==='cards';$('#table-view').hidden=cards;$('#card-view').hidden=!cards;update()}));update();
}
function initDatasets(){const input=$('#dataset-search');if(!input)return;let group='';const update=()=>{$$('[data-dataset]').forEach(r=>r.hidden=!!((group&&r.dataset.group!==group)||(input.value&&!r.dataset.search.includes(input.value.toLowerCase()))) )};$$('[data-dataset-group]').forEach(b=>b.addEventListener('click',()=>{group=group===b.dataset.datasetGroup?'':b.dataset.datasetGroup;$$('[data-dataset-group]').forEach(x=>x.classList.toggle('active',x===b&&!!group));update()}));input.addEventListener('input',update);$('#dataset-clear').addEventListener('click',()=>{group='';input.value='';$$('[data-dataset-group]').forEach(x=>x.classList.remove('active'));update()})}
$$('[data-dialog]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.dialog).showModal()));$$('.dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
function initDiffs(){
 const source=$('#version-diffs');if(!source)return;const diffs=JSON.parse(source.textContent),from=$('#diff-from'),to=$('#diff-to'),section=$('#diff-section'),summary=$('#diff-summary'),list=$('#diff-list'),error=$('#compare-error'),panel=$('#diff-panel');
 const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const render=()=>{const d=diffs[`${from.value}--${to.value}`];if(!d){const reverse=diffs[`${to.value}--${from.value}`];error.hidden=false;error.innerHTML=reverse?'<h3>Choose an earlier “From” version</h3><p>Static comparisons are stored in chronological order.</p>':'<h3>No comparison available</h3>';summary.hidden=true;list.innerHTML='';return}error.hidden=true;summary.hidden=false;const s=d.summary;summary.innerHTML=`<h2>${esc(d.from)} → ${esc(d.to)}</h2>${[['+','papers added',s.papersAdded,'added'],['−','papers removed',s.papersRemoved,'removed'],['~','paper records updated',s.papersUpdated,'modified'],['+','datasets added',s.datasetsAdded,'added'],['~','benchmarks corrected',s.benchmarksCorrected,'modified'],['~','sections revised',s.sectionsRevised,'modified']].map(x=>`<div class="${x[3]}"><b>${x[0]} ${x[2]}</b><span>${x[1]}</span></div>`).join('')}`;const label={added:'+ Added',removed:'− Removed',modified:'~ Modified',reclassified:'↔ Reclassified'};list.innerHTML=d.changes.map(c=>`<article class="diff-block" data-section="${esc(c.section)}"><header><span class="badge ${esc(c.type)}">${label[c.type]||esc(c.type)}</span><strong>${esc(c.section)}</strong></header><p class="summary-description">${label[c.type]||esc(c.type)} · ${esc(c.section)}</p><div class="diff-lines">${c.old?`<p class="line removed"><span>−</span>${esc(c.old)}</p>`:'<p class="line empty"><span>−</span>No earlier value</p>'}${c.new?`<p class="line added"><span>+</span>${esc(c.new)}</p>`:'<p class="line empty"><span>+</span>No later value</p>'}</div></article>`).join('');const sections=[...new Set(d.changes.map(c=>c.section))];section.innerHTML='<option value="">All sections</option>'+sections.map(x=>`<option>${esc(x)}</option>`).join('');history.replaceState({},'',`${location.pathname}?from=${encodeURIComponent(d.from)}&to=${encodeURIComponent(d.to)}`)};
 $('#compare-submit').addEventListener('click',render);section.addEventListener('change',e=>$$('.diff-block').forEach(b=>b.hidden=!!e.target.value&&b.dataset.section!==e.target.value));$$('[data-diff-view]').forEach(b=>b.addEventListener('click',()=>{panel.dataset.view=b.dataset.diffView;$$('[data-diff-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))})}));const q=new URLSearchParams(location.search);if(q.get('from'))from.value=q.get('from');if(q.get('to'))to.value=q.get('to');
}
$$('#copy-bibtex,.copy-citation').forEach(button=>button.addEventListener('click',async e=>{try{await navigator.clipboard.writeText(e.target.dataset.copy);e.target.textContent='Copied';setTimeout(()=>e.target.textContent='Copy BibTeX',1800)}catch{e.target.textContent='Select text below to copy'}}));
$('#survey-version')?.addEventListener('change',e=>{if(e.target.value===e.target.dataset.currentVersion)return;location.href=(base==='/'?'':base.replace(/\/$/,''))+`/versions/${e.target.value}/`});
const maintenanceSummary=$('.workflow-home>div');
if(maintenanceSummary){const link=document.createElement('a');link.className='maintenance-detail-link';link.href=(base==='/'?'':base.replace(/\/$/,''))+'/maintenance/';link.textContent='See full maintenance details →';maintenanceSummary.append(link)}
initExplorer();initDatasets();initDiffs();
